### ISSUE TITLE
Use sd-webui-controlnet from Unprompted

### ISSUE THREAD

**Issue by Banbury** [ThereforeGames/unprompted#102]
I couldn't find any documentation, on how to use `sd-webui-controlnet` in Unprompted. This is the one feature I would find most interesting about Unprompted, as it is very tedious to set up several ControlNets. I'm consistently missing one ore more settings. Unprompted could be very helpful to store useful presets.

**Comment by aallcg** [comment]
would also like to know!

**Comment by ThereforeGames** [comment]
Hi @Banbury and @aallcg,

Finally got around to implementing `[set]` compatibility with ControlNet settings :)

In the next update, you will be able to manage your CN units as follows:

```
[sets controlnet_0_enabled=1 controlnet_3_weight=0.75]
```

It's a huge timesaver. You can even create a default CN setup by inserting the shortcode into `ui-config.json` or `Unprompted.Config.templates.default`.

The update should be available in the next 24h, so keep an eye out for it!

**Comment by aallcg** [comment]
Awesome! Thanks for iterating on this :)

**Comment by MotherSoraka** [comment]
Hi, no matter what i do i cant use ControlNet through unprompted, i did read the manual, renamed my controlnet models, copied the yaml file and renamed that one too... but still no use.

can someone show me a simple example please?

**Comment by ThereforeGames** [comment]
Simple example of using ControlNet through Unprompted:

```
[sets cn_0_enabled=1 cn_0_weight=0.5 cn_0_pixel_perfect=1 cn_0_module=softedge_hed cn_0_model=controlnet11Models_softedge]Your prompt goes here
```

You may need to adjust `cn_0_module` and `cn_0_model` to your own filenames.
