### ISSUE TITLE
Switch shortcode always returns default case

### ISSUE THREAD

**Issue by Vanhall** [ThereforeGames/unprompted#107]
Switch shortcode always returns default case, even if a more concrete case was matched. Following code, for example:
```
[set foo]one[/set]
[switch foo]
	{case "one"}one{/case}
	{case "two"}two{/case}
	{case}default{/case}
[/switch]
```
returns `one default`.

**Comment by ThereforeGames** [comment]
Fixed in v8.1.0. Thank you for bringing it to my attention!
