### ISSUE TITLE
set sets variable only once

### ISSUE THREAD

**Issue by f8upd8** [ThereforeGames/unprompted#11]
Only affects settings once per generation, not considering batch count or batch size.
I'd really want to bring some diversity by modifying various variable but it looks like it's not there yet

random_cfg.txt

[choose]
2
3
4
5
6
7
8
9
10
11
12
13
14
15
[/choose]

prompt:
[set cfg_scale][file random_cfg][/set]

**Comment by ThereforeGames** [comment]
Hi @MalOMaw,

I believe this is a limitation of Automatic's extension framework - there isn't an obvious way of specifying things like CFG Scale on a per-image basis.

We can possibly hijack the run() routine to get around this, which is actually what I ended up doing for my [txt2img2img](https://github.com/ThereforeGames/txt2img2img) script, but it's something I need to implement carefully. Will take some time.

**Comment by f8upd8** [comment]
> Hi @MalOMaw,
> 
> I believe this is a limitation of Automatic's extension framework - there isn't an obvious way of specifying things like CFG Scale on a per-image basis.
> 
> We can possibly hijack the run() routine to get around this, which is actually what I ended up doing for my [txt2img2img](https://github.com/ThereforeGames/txt2img2img) script, but it's something I need to implement carefully. Will take some time.

No problem! The more solid this extension is, the better :)
Thanks for your hard work

**Comment by ThereforeGames** [comment]
> I believe this is a limitation of Automatic's extension framework - there isn't an obvious way of specifying things like CFG Scale on a per-image basis.

Fortunately, we no longer live in the dark ages and it's possible to change Stable Diffusion variables on a per-image basis.

I retooled the batch processing code in v9.8.0 so you can take advantage of this. Let me know if it gives you any trouble. Thanks.
