### ISSUE TITLE
about controlnet

### ISSUE THREAD

**Issue by shiyuleixia** [ThereforeGames/unprompted#113]
when controlnet processing is finished,is there need some code to restore the sd_model structure? like:

self.before_network.restore(p.sd_model.model.diffusion_model)

**Comment by ThereforeGames** [comment]
Hi @shiyuleixia,

Thank you for reaching out!

As for your question: sort of. Unprompted creates a clone of the `p` object that precludes ControlNet processing. Shortcodes such as `[zoom_enhance]` can reference this object with `self.Unprompted.p_copy`.

You may be able to use this object with the `restore()` method - I'm not sure, I haven't tried. If you can tell me more about your use case, I may be able to provide better help.

**Comment by Dawgmastah** [comment]
Is there a way to get Zoomenhance working with the latest controlnets?
Usually it becomes a jumbled mess in the face as it sees some of the controlnet lines

**Comment by ThereforeGames** [comment]
Latest versions of Unprompted automatically disable ControlNet before `[zoom_enhance]` fires, but please feel free to open an issue if it's still giving you any trouble.
