### ISSUE TITLE
Suggestion: Keep the linebreak

### ISSUE THREAD

**Issue by kehao95** [ThereforeGames/unprompted#115]
Can we keep the linebreaks exists in the template. This won't change any behaviour, but will be helpfur for user to debug changes.

**Comment by ThereforeGames** [comment]
Hi @kehao95,

Thanks for reaching out!

Removal of linebreaks is controlled by your `Unprompted.Config.syntax.sanitize_before` setting. You can try adding the following to your config_user.json file:

```
"syntax":
{
  "sanitize_before":{"\t":""}
}
```

(`"\t"` is for removing tabs, normally this setting also includes `"\n"` for linebreaks)

Or, add this directly to a template if you don't want to make it a global change:

```
[config]{"syntax":{"sanitize_before":{"\t":""}}}[/config]
```

Let me know if you have any questions.
