### ISSUE TITLE
How to fix extra fingers and wrong hand?

### ISSUE THREAD

**Issue by xunxun** [ThereforeGames/unprompted#116]
[after]{zoom_enhance mask-"fingers" replacement="closeup hand" max_denoising_strength-0.9}[/after]
this doesn't seems to work but the face is enhanced.

**Comment by ThereforeGames** [comment]
Hi @xunxun,

Sorry for the late reply, I'm going through some older issues today.

There's a typo in your code. `mask-"fingers"` needs an equals sign. Since you're not setting `mask` to anything, it still has the default value of `face`. Same goes for `max_denoising_strength`. Hope that helps.
