### ISSUE TITLE
Use a custom mask in [zoom_enhance]

### ISSUE THREAD

**Issue by Laidawang** [ThereforeGames/unprompted#117]
I want to use a custom mask to do zoom_enhance, what should I do?
For example, use seganything instead of clipseg.

**Comment by ThereforeGames** [comment]
Hi Laidawang,

You can add `mask_method` to your `[zoom_enhance]` block as follows:

```
[after]{zoom_enhance mask_method="clip_surgery"}[/after]
```

P.S. I still need to add this as an option to the Wizard, so it must be used directly in the code for now.
