### ISSUE TITLE
Can't update the extension from automatic tab, any way to update manually?

### ISSUE THREAD

**Issue by aniketgore** [ThereforeGames/unprompted#12]
I only see unknown as state when I try to update the extension. Is there a way to manually do this?

**Comment by ThereforeGames** [comment]
Hi @aniketgore,

Hmm - I wonder if I need to add anything to the repo to allow for automatic updates. Let me do some research.

In the meantime, you can update the extension by downloading the repo from GitHub and extracting the files to your `automatic-stable-diffusion-webui\extensions\unprompted` directory, overwriting what's already there.

**Comment by ThereforeGames** [comment]
Hi,

The update feature seems to work on my device. Could you check the following video recording and let me know if you're seeing the same thing in your UI?

![brave_9Ju7iKVk72](https://user-images.githubusercontent.com/95403634/200115011-6162eade-a675-4719-a908-2226e534dd96.gif)

**Comment by aniketgore** [comment]
don't know what happened. I had to remove the folder, and then redownload it after restart. Now I see the Installed versions as latest.

**Comment by ThereforeGames** [comment]
Strange. Glad to hear it works now!
