### ISSUE TITLE
Error at startup.

### ISSUE THREAD

**Issue by mokumoku4865** [ThereforeGames/unprompted#122]
=== 日本語 ===
この拡張機能を最新版にしてから起動すると次のような不具合があります。
1.起動後にWebuiにunpromptedが表示されない。
2.画像生成してもテキストファイルの内容が反映されない。
例えば、[file "common/text"]のままプロンプトになる。

=== English ===
The following problems occur when starting this extension after the latest version is installed.
1. "unprompted" is not displayed in webui after startup.
2. The content of the text file is not reflected even if an image is generated.
For example, [file "common/text"] is still prompted.

=== Log ===
Launching Web UI with arguments: --xformers --opt-channelslast --upcast-sampling --medvram --no-half-vae --no-hashing --disable-nan-check --listen --enable-insecure-extension-access --autolaunch
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: D:\flat\userData\features\stable-diffusion-webui\repository\extensions\Stable-Diffusion-Webui-Civitai-Helper\setting.json
Civitai Helper: No setting file, use default
Error loading script: unprompted.py
Traceback (most recent call last):
  File "D:\flat\userData\features\stable-diffusion-webui\repository\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\flat\userData\features\stable-diffusion-webui\repository\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\flat\userData\features\stable-diffusion-webui\repository\extensions\unprompted\scripts\unprompted.py", line 246
                                                                obj = gr.Checkbox(label=this_label,value=bool(int(content)),info=_info)
                                                                ^^^
IndentationError: expected an indented block after 'elif' statement on line 244

**Comment by saftle** [comment]
I'm sadly getting the same issue after updating today. Unprompted no longer works at all.

**Comment by Zetaphor** [comment]
There's a syntax error in the script, it would benefit from the use of a formatter

**Comment by balrog69-420** [comment]
its quick fix. go to your extensions folder , into the unpromtped folder, and scripts. something like F:\stable-diffusion-webui\extensions\_unprompted\scripts

open unprompted.py to edit it. scroll down to line 246 where the error is and youll see one line 

obj = gr.Checkbox(label=this_label,value=bool(int(content)),info=_info)

that needs a tab (indent) so its inline with the other obj lines around it 
(press tab to add an indent so its inline with the other) obj = gr.Checkbox(label=this_label,value=bool(int(content)),info=_info)

like the others thats start with obj, hope this helps. 

`if (block_name == "textbox"):
									if "_placeholder" in kwargs: this_placeholder = kwargs["_placeholder"]
									else: this_placeholder = str(content)
									obj = gr.Textbox(label=this_label,max_lines=1,placeholder=this_placeholder,info=_info)
								elif (block_name == "checkbox"):

                                                                        obj = gr.Checkbox(label=this_label,value=bool(int(content)),info=_info)
								elif (block_name == "number"): obj = gr.Number(label=this_label,value=int(content),interactive=True,info=_info)
								elif (block_name == "dropdown"): obj = gr.Dropdown(label=this_label,value=content,choices=kwargs["_choices"].split(Unprompted.Config.syntax.delimiter),info=_info)
								elif (block_name == "radio"): obj = gr.Radio(label=this_label,choices=kwargs["_choices"].split(Unprompted.Config.syntax.delimiter),interactive=True,value=content)
								elif (block_name == "slider"):
									obj = gr.Slider(label=this_label,value=int(content),minimum=kwargs["_minimum"],maximum=kwargs["_maximum"],step=kwargs["_step"],info=_info)
							
								setattr(obj,"do_not_save_to_config",True)
							return("")
`

im trying to insert code to show it clearer but idk what im doing.

sorry if its confusing .

**Comment by ThereforeGames** [comment]
Shoot, that's what I get for trying to merge a PR with the web editor. Sorry about that. Can you try the latest update and let me know if the error persists?

**Comment by balrog69-420** [comment]
yeh after my attempt at fixing it i think i broke something and it wasnt masking anything at all (just added a new picture ontop of the face, very odd) so i deleted the extension and reinstalled it from the latest one and now everything is working fine. thanks!

**Comment by ThereforeGames** [comment]
Glad to hear it's working now! I'll mark the issue as resolved.

**Comment by mokumoku4865** [comment]
It worked correctly! Thank you very much.
