### ISSUE TITLE
pix2pix_zero

### ISSUE THREAD

**Issue by HeavyTony2** [ThereforeGames/unprompted#128]
This one is documented for now. Is it only working with Pix2Pix checkpoints? I'm trying to use it with an inpainting one and I get this error:
```
    return(self.shortcode_objects[f"{keyword}"].run_block(pargs, kwargs, context, content))
TypeError: Shortcode.run_block() takes 4 positional arguments but 5 were given
```

**Comment by ThereforeGames** [comment]
Hi @HeavyTony2,

Thank you for reaching out.

I ceased working on the `[pix2pix_zero]` shortcode after realizing it wasn't exactly what the authors claimed in their paper ("no finetuning required" is a stretch). More info here:

https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/7711#discussioncomment-4952579

As far as I know, pix2pix_zero does not utilize the same architecture as traditional pix2pix. Authors say it should be compatible with any checkpoint.

You'll need to change the hardcoded model_path in `unprompted/shortcodes/stable_diffusion/pix2pix_zero.py` on line 33:

```
model_path = "T:\\code\python\\automatic-stable-diffusion-webui\\models\\diffusers\\sd14"
```

Model must be in diffusers format.

**Comment by HeavyTony2** [comment]
> Model must be in diffusers format.

Does it have to be absolutely SD 1.4 or can it be SD 1.5? Not gonna lie, it seems to be quite complicated just to try it.

**Comment by HeavyTony2** [comment]
I was thinking about that, do you think Unprompted could be used to port this model for A1111? https://github.com/Fantasy-Studio/Paint-by-Example

**Comment by ThereforeGames** [comment]
Closing due to removal of `[pix2pix_zero]` shortcode.

> I was thinking about that, do you think Unprompted could be used to port this model for A1111? https://github.com/Fantasy-Studio/Paint-by-Example

I only briefly played around with this tech but I wasn't especially impressed with the results compared to ControlNet or inpainting models. I'll consider adding it if I find a compelling reason to.
