### ISSUE TITLE
This zoom enhance hasn't worked for a while now

### ISSUE THREAD

**Issue by freke70** [ThereforeGames/unprompted#136]
No idea what the probem is here.
I removed almost all extentions.
Updated to latest automatic1111 (vlad)

[if batch_index=0][after][zoom_enhance mask="face" replacement="face" mask_sort_method="left-to-right" upscale_method="Nearest Neighbor" downscale_method="Lanczos" blur_size=0.03 cfg_scale_min=7.0 denoising_max=0.65 mask_size_max=0.5 min_area=50.0 contour_padding=0.0 upscale_width=512.0 upscale_height=512.0][/after][/if]

`Running script postprocess: /home/me/automatic/extensions/unprompted/scripts/unprompted.py: ShortcodeRenderingError
╭──────────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────────────────────────────────────────────╮
│ /home/me/automatic/extensions/unprompted/lib_unprompted/shortcodes.py:120 in render                                                                                                      │
│                                                                                                                                                                                                   │
│   119 │   │   try:                                                                                                                                                                                │
│ ❱ 120 │   │   │   return str(self.handler(self.token.keyword, self.pargs, self.kwargs, context                                                                                                    │
│   121 │   │   except Exception as ex:                                                                                                                                                             │
│                                                                                                                                                                                                   │
│ /home/me/automatic/extensions/unprompted/lib_unprompted/shared.py:65 in handler                                                                                                          │
│                                                                                                                                                                                                   │
│    64 │   │   │   │   def handler(keyword, pargs, kwargs, context):                                                                                                                               │
│ ❱  65 │   │   │   │   │   return(self.shortcode_objects[f"{keyword}"].run_atomic(pargs, kwargs                                                                                                    │
│    66 │   │   │   else:                                                                                                                                                                           │
│                                                                                                                                                                                                   │
│ /home/me/automatic/extensions/unprompted/shortcodes/stable_diffusion/zoom_enhance.py:398 in run_atomic                                                                                   │
│                                                                                                                                                                                                   │
│   397 │   │   │   │   │   │   self.Unprompted.log(f"Sharpening the fixed image by {sharpen_amo                                                                                                    │
│ ❱ 398 │   │   │   │   │   │   fixed_image = unsharp_mask(fixed_image,sharpen_amount)                                                                                                              │
│   399                                                                                                                                                                                             │
│                                                                                                                                                                                                   │
│ /home/me/automatic/extensions/unprompted/shortcodes/stable_diffusion/zoom_enhance.py:42 in unsharp_mask                                                                                  │
│                                                                                                                                                                                                   │
│    41 │   │   │   image = numpy.array(image)                                                                                                                                                      │
│ ❱  42 │   │   │   blurred = cv2.GaussianBlur(image, kernel_size, sigma)                                                                                                                           │
│    43 │   │   │   sharpened = float(amount + 1) * image - float(amount) * blurred                                                                                                                 │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
error: OpenCV(4.5.5) :-1: error: (-5:Bad argument) in function 'GaussianBlur'
> Overload resolution failed:
>  - src data type = 0 is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'

The above exception was the direct cause of the following exception:

╭──────────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────────────────────────────────────────────╮
│ /home/me/automatic/modules/scripts.py:446 in postprocess                                                                                                                                 │
│                                                                                                                                                                                                   │
│   445 │   │   │   │   script_args = p.script_args[script.args_from:script.args_to]                                                                                                                │
│ ❱ 446 │   │   │   │   script.postprocess(p, processed, *script_args)                                                                                                                              │
│   447 │   │   │   except Exception as e:                                                                                                                                                          │
│                                                                                                                                                                                                   │
│ /home/me/automatic/extensions/unprompted/scripts/unprompted.py:544 in postprocess                                                                                                        │
│                                                                                                                                                                                                   │
│   543 │   │   for i in Unprompted.after_routines:                                                                                                                                                 │
│ ❱ 544 │   │   │   Unprompted.shortcode_objects[i].after(p,processed)                                                                                                                              │
│   545 │   │   self.allow_postprocess = True                                                                                                                                                       │
│                                                                                                                                                                                                   │
│                                                                                      ... 4 frames hidden ...                                                                                      │
│                                                                                                                                                                                                   │
│ /home/me/automatic/extensions/unprompted/lib_unprompted/shortcodes.py:59 in <genexpr>                                                                                                    │
│                                                                                                                                                                                                   │
│    58 │   def render(self, context):                                                                                                                                                              │
│ ❱  59 │   │   return ''.join(child.render(context) for child in self.children)                                                                                                                    │
│    60                                                                                                                                                                                             │
│                                                                                                                                                                                                   │
│ /home/me/automatic/extensions/unprompted/lib_unprompted/shortcodes.py:124 in render                                                                                                      │
│                                                                                                                                                                                                   │
│   123 │   │   │   msg += f"'{self.token.keyword}' shortcode in line {self.token.line_number}."                                                                                                    │
│ ❱ 124 │   │   │   raise ShortcodeRenderingError(msg) from ex                                                                                                                                      │
│   125                                                                                                                                                                                             │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
ShortcodeRenderingError: An exception was raised while rendering the 'zoom_enhance' shortcode in line 1.
`

**Comment by ThereforeGames** [comment]
Hi @freke70,

Thank you for reaching out. According to the error log, there was an issue with the sharpening filter in `[zoom_enhance]`. Please try updating to v9.0.1 and let me know if the issue persists.

If it does, you can temporarily disable the filter by adding `sharpen_amount=0` to your `[zoom_enhance]` calls.

**Comment by freke70** [comment]
Thanks so much, it's working once again.
I love zoom_enhance, so it was a real bummer to go without it.
Thanks for the prompt fixing :)

I bought one of the template packs to show some support

**Comment by ThereforeGames** [comment]
Awesome! Glad to hear it's working again, and thanks so much for your support. :)
