### ISSUE TITLE
Switch/Case after 9.0 update

### ISSUE THREAD

**Issue by eanism** [ThereforeGames/unprompted#137]
So far, most of the updated preprocess_blocks() changes I've tested are working great. However I am not able to get switch structures to behave correctly. It seems the code within the case isn't being executed. Sample code:
`[sets control="test"]
[sets nvar="Unset"]
[switch control]
	[case "test"]
		[sets nvar="Match"]
	[/case]
	[case "untest"]
		[sets nvar="No Match"]
	[/case]
[/switch]
[get nvar]`
This continues to return "Unset", when the expected result is "Match". This test is based on the new sample provided in bodysnatcher.

**Comment by ThereforeGames** [comment]
Hi @eanism,

Thank you bringing this to my attention - the `[switch]` `[case]` blocks should now behave correctly in v9.0.1.

**Comment by eanism** [comment]
Confirmed working, thank you!

**Comment by ThereforeGames** [comment]
Sure thing! I actually just released another hotfix for the default `[case]` statement, so make sure you grab that. Version number unchanged.
