### ISSUE TITLE
Please enable setting the image with controlnet json

### ISSUE THREAD

**Issue by magicbot42** [ThereforeGames/unprompted#139]
I'm not using img2img, but txt2img, so a single image isn't automatically set across the controlnets for me with txt2img.  It sort of defeats the automation if we also have to manually go to each control net in the multicontrol net and specificy the image to use.  I'd like to iterate over a file path list and set the images to be used for generating movies with multi-controlnet in txt2img.

**Comment by magicbot42** [comment]
Did a little sleuthing, and found that it "should" already be implemeted to take cn_0_image="filename" type agruments in the json file, and after turning on debug for the extension on the config file I see this: 

![image](https://user-images.githubusercontent.com/3104806/235291835-0eca39fe-fab8-429b-83aa-dea11f0e967c.png)

Then I found the line causing the issue in lib_unprompted\shared.py: 

![image](https://user-images.githubusercontent.com/3104806/235291911-db89c77b-1fc8-4449-bc9a-826aaacef4b2.png)

My installation of automatic1111 is using python 3.10.6.  I installed Pillow with pip install Pillow and pip install Image.   It was already installed.   I notice that while I can't import Image with "pil", I can import it with "PIL" in python 3.10.6:

![image](https://user-images.githubusercontent.com/3104806/235291998-638dab5c-e5c9-4a8e-a6b1-c6fb183a7e3d.png)

**Comment by magicbot42** [comment]
Well doesn't look like 
from PIL import Image works for me either: 
![image](https://user-images.githubusercontent.com/3104806/235293847-dc6b6f08-211f-42df-b504-418d86735562.png)

**Comment by magicbot42** [comment]
Figured out from the dtype error that the image has to be an numpy array.   
imageio seems to create numpy array image by default, and works.  

![image](https://user-images.githubusercontent.com/3104806/235297466-29d4c7d8-14ce-4a4b-9909-593c35b8c7d1.png)

Still don't know what the deal is with the missing "pil" module, but this works for now.

**Comment by magicbot42** [comment]
Thanks for the amazing tool.

**Comment by ThereforeGames** [comment]
Hi @zainhomer,

Thank you for reaching out! I have updated `shared.py` with your findings in v9.1.1.
