### ISSUE TITLE
Video tutorial

### ISSUE THREAD

**Issue by Tobe2d** [ThereforeGames/unprompted#14]
Could you make a video tutorial showing us how to use this?

**Comment by ThereforeGames** [comment]
Hi @Tobe2d,

Sure, I can try to find some time to record a video tutorial - what sort of topics would you be interested in? Are you simply looking for a video version of the [Starter Guide](https://github.com/ThereforeGames/unprompted/blob/main/docs/GUIDE.md) or were you hoping for something a bit more advanced?

**Comment by Tobe2d** [comment]
It will be realy good to see both Starter Guide and Advanced
+ if you can make one for using those special "Fantasy Card Templates"
I got them and still dont know how to sue them ;-)

**Comment by Tobe2d** [comment]
Any news on this?

**Comment by Tobe2d** [comment]
I havent heard back about the same. could you make update us on what is the status?

**Comment by Tobe2d** [comment]
@ThereforeGames

**Comment by Tobe2d** [comment]
I have no Idea why you are ignoring this

**Comment by ThereforeGames** [comment]
Hi @Tobe2d,

I didn't have much to share on this topic until now - I finally got around to setting up my recording software and have put together an overview on the new DemonCrawl Avatar Generator:

https://youtu.be/4xnL7kgs5Rw

While it's not the Fantasy Card Template, much of what I say in the video applies to both products. The Fantasy template now has a similar "Wizard GUI" that makes it a lot easier to use.

I hope the video clarifies some things for you!
