### ISSUE TITLE
I cant call [set sd_model] from after blocks

### ISSUE THREAD

**Issue by o0oradaro0o** [ThereforeGames/unprompted#141]
I want to change models then do an img2img and zoom_enhance but every method i use seems to be blocked, is this intentional? [set sd_model] still works outside the after blocks.

I am running v9.1.1 and have tried using sets instead, tried {}, tried putting the set command in a template file and calling the file and everything i can think of, i cant seem to swap the model in an after block.

**Comment by ThereforeGames** [comment]
Hi @o0oradaro0o,

As of Unprompted v9.8.3, you can now modify Stable Diffusion variables within the `[after]` block! The WebUI will sync with your Unprompted variables at the start of any img2img task, including `[zoom_enhance]` and `[img2img]`.

Let me know if you have any trouble with it.
