### ISSUE TITLE
Error with install.py

### ISSUE THREAD

**Issue by MathewPazhur** [ThereforeGames/unprompted#142]
When running install.py during installation, I get the error:

```
line 1, in <module>
    import launch, shutil, os
ModuleNotFoundError: No module named 'launch'
```

When I try to pip install 'launch' it says I need flowdas-meta which no longer has a page on pypi.

**Comment by ThereforeGames** [comment]
Hi @MathewPazhur,

Sorry for the delayed response.

`launch` refers to the launch.py file included with the Automatic WebUI. It provides the `run_pip()` method that most extensions (including Unprompted) use for installing their dependencies into your virtual environment.

I would first try disabling your other extensions to see if they are somehow overriding the meaning of `launch`. If that doesn't fix the issue, you may need to reinstall the WebUI.

**Comment by ThereforeGames** [comment]
Closed due to lack of activity - please let me know if `install.py` is still giving you trouble. Thanks.
