### ISSUE TITLE
Missing update_stable_diffusion_vars function in latest checkin

### ISSUE THREAD

**Issue by magicbot42** [ThereforeGames/unprompted#150]
Seeing a missing function with the latest checking, and getting this traceback:  

![image](https://github.com/ThereforeGames/unprompted/assets/3104806/8bd053fb-5d99-4a76-91d1-a37e7b985e7d)

**Comment by magicbot42** [comment]
I tried commenting out that line, but then my controlnets are no longer loading via the txt2img tab.   So I reverted to the may 4th commit to get back to a working state again:  8801f32.

**Comment by ThereforeGames** [comment]
Hi @zainhomer,

Thank you for reaching out - I have a few diagnostic questions:

- Did you restart your WebUI after applying the update?
- What is your prompt?
- The function in question is located at `_unprompted/scripts/unprompted.py` on line 303. Can you confirm that it's there? (e.g. `def update_stable_diffusion_vars(self,this_p)` )

Thanks!

**Comment by ThereforeGames** [comment]
Closing as stale, but please let me know if the problem persists.
