### ISSUE TITLE
Wildcards not supported properly for img2img/controlnet batch

### ISSUE THREAD

**Issue by ghost** [ThereforeGames/unprompted#155]
After dynamic prompts stopped working and I did not want to use the ancient wildcards script, I decided to use unprompted for wildcards. They work pretty well except when you batch through img2img or controlnet - it stops updating the prompt inbetween images which makes the wildcards not so useful for this use case

**Comment by ThereforeGames** [comment]
Hi ghost,

I have added support for the batch img2img tab in Unprompted v9.4.0. Let me know if it gives you any trouble. Thanks!
