### ISSUE TITLE
Secondary shortcodes inside [choose] cause errors

### ISSUE THREAD

**Issue by Siberpone** [ThereforeGames/unprompted#160]
Using secondary shortcodes in [choose] items causes errors. Exapmle code to reproduce:
```
[set x]color[/set]
[choose]
    [file "common/{get x}"]
    some other stuff
[/choose]
```
It seems the issue was introduced in bfa6fb66e8c3ea6214c5c35ccf2e2848e7a0ba20. The above code works as intended in 9.0.1.

**Comment by ThereforeGames** [comment]
Hi @Siberpone,

I believe I fixed this in v9.3.1, but let me know if the issue persists after updating. Thanks!
