### ISSUE TITLE
[file somefile] greatly skews/amplifies hires,fix denoising 

### ISSUE THREAD

**Issue by magicbot42** [ThereforeGames/unprompted#161]
With latest version of stable diffusion as of today and latest version of umprompted as of today and no other extensions added, I'm noticing that txt2img denoising no longer works as it is supposed to when the prompt is read from a [file somefile] shortcode.  The denoising creates very drastic changes in the image when the prompt is read through a simple [file ] shortcut vs when it's not. 

Here's how to repeat what I'm seeing.  
1. Take any prompt / negative prompt from civitai or elsewhere
2. Turn on highres fix with denoising anywhere above .7  (anything above .5 is noticable, but very noticable after .7)
3. Using txt2img drop in the prompt/negative prompt.
4. Generate an image, and notice the how much the denoising has affected the image.
5. Add the same prompt/negative prompt into .txt files and load with [file filepath] for each
6. Generate again.  Notice the drastic effect denoising has when read through a [file ] shortcut vs when not. 

Not sure why this is, but it wasn't always the case.  I've recently updated everything and this started happening.  I narrowed it down to a fresh install of SD automatic1111, and only unprompted extension.  

Something seems to be causing the denoising part of the processing to not consider the prompt or something.   Love this extension but this issue has made it sort of unworkable to use it.  Hope it can be fixed.

**Comment by ThereforeGames** [comment]
Hi @magicbot42,

Thank you for bringing this to my attention.

It looks like the WebUI recently added a few variables related to highres. fix - the `hr_prompt` var wasn't accounting for shortcodes which is why you would see a discrepancy when calling `[file]` for example.

This should work correctly in Unprompted v9.5.0, but please let me know if the issue persists.

**Comment by magicbot42** [comment]
Verified it works now.  Thanks!
