### ISSUE TITLE
no debug mode in v9.4.0 of config.json

### ISSUE THREAD

**Issue by gboxentertainment** [ThereforeGames/unprompted#163]
Was debug mode replaced in the latest version? It's missing in config.json and adding it in does nothing.

**Comment by ThereforeGames** [comment]
Hi @gboxentertainment,

In v9.0.0, the `debug` option was removed in favor of the more-flexible `log_contexts` option.

The console will print `RESULT`, `WARNING`, and `ERROR` messages by default, but you can add `DEBUG` to this list if you want verbose output:

```
{
	"log_contexts":"RESULT,WARNING,ERROR,DEBUG"
}
```

I hope that helps!
