### ISSUE TITLE
The txt2img example doesn't work

### ISSUE THREAD

**Issue by cian0** [ThereforeGames/unprompted#164]
[after][sets cfg_scale=15 prompt="horse"][txt2img][/after]dog

This will generate 2 times but both just outputs a dog

**Comment by cian0** [comment]
![image](https://github.com/ThereforeGames/unprompted/assets/1121189/e6a5376e-1a36-4fd9-8bbe-4480aa6abe27)

**Comment by ThereforeGames** [comment]
Hi @cian0,

This issue has been resolved in Unprompted v9.5.1. Thank you for bringing it to my attention!

**Comment by cian0** [comment]
Cool that was fast!
