### ISSUE TITLE
Refresh templates in Wizard?

### ISSUE THREAD

**Issue by HWiese1980** [ThereforeGames/unprompted#172]
It's either I am visually impaired or there is no way to refresh the available templates in the Unprompted Wizard, other than restarting A1111, is that correct? 

I would like to have a button that does exactly that. Refreshing the templates, that is, not restarting A1111. Thanks!

**Comment by ThereforeGames** [comment]
Hi @HWiese1980,

You're not blind. :-) I need to do some research to figure out how to implement a refresh button for this - it must create a lot of new Gradio UI components in addition to updating the dropdown list.

I think the ControlNet extension may have similar functionality, so I may take a peek at their source code when I find time.

It's a good suggestion though, thanks!

EDIT: Oh, I should also mention that you don't have to restart the entire application - you can use the "Reload UI" button in the settings which is considerably faster.

**Comment by HWiese1980** [comment]
Hah, thank you, that would be awesome! I already started questioning my own judgement. :-D

And you're welcome :-D

**Comment by ThereforeGames** [comment]
Hi @HWiese1980,

You can now refresh templates and shortcodes in Unprompted v9.15.0! This required me to refactor a surprisingly large amount of code, so please let me know if you run into any issues in the new version. Thanks.
