### ISSUE TITLE
File loading does not work.

### ISSUE THREAD

**Issue by mokumoku4865** [ThereforeGames/unprompted#177]
After updating SD Next and Umprompt, I get the following error and can no longer load files, making them unusable.

`13:01:16-441720 ERROR    Running script process: D:\automatic\extensions\unprompted\scripts\unprompted.py:
                         AttributeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\automatic\modules\scripts.py:406 in process                                                                       │
│                                                                                                                      │
│   405 │   │   │   │   args = p.per_script_args.get(script.title(), p.script_args[script.args_f                       │
│ ❱ 406 │   │   │   │   script.process(p, *args, **kwargs)                                                             │
│   407 │   │   │   │   s.append(f'{script.title()}:{round(time.time()-t0, 2)}s')                                      │
│                                                                                                                      │
│ D:\automatic\extensions\unprompted\scripts\unprompted.py:565 in process                                              │
│                                                                                                                      │
│   564 │   │   if sd_models.model_data.sd_model:                                                                      │
│ ❱ 565 │   │   │   if sd_models.model_data.sd_model.is_sdxl: Unprompted.shortcode_user_vars["sd                       │
│   566 │   │   │   elif sd_models.model_data.sd_model.is_sd2: Unprompted.shortcode_user_vars["s                       │
│                                                                                                                      │
│ D:\automatic\venv\lib\site-packages\torch\nn\modules\module.py:1614 in __getattr__                                   │
│                                                                                                                      │
│   1613 │   │   │   │   return modules[name]                                                                          │
│ ❱ 1614 │   │   raise AttributeError("'{}' object has no attribute '{}'".format(                                      │
│   1615 │   │   │   type(self).__name__, name))                                                                       │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'LatentDiffusion' object has no attribute 'is_sdxl'
Loading weights: D:\automatic\models\Lora\add_detail.safetensors ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/37.9 MB -:--:--
Loading weights: D:\automatic\models\Lora\flat2.safetensors ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/6.9 MB -:--:--
13:01:16-770895 ERROR    Running script process batch: D:\automatic\extensions\unprompted\scripts\unprompted.py:
                         KeyError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\automatic\modules\scripts.py:430 in process_batch                                                                 │
│                                                                                                                      │
│   429 │   │   │   │   args = p.per_script_args.get(script.title(), p.script_args[script.args_f                       │
│ ❱ 430 │   │   │   │   script.process_batch(p, *args, **kwargs)                                                       │
│   431 │   │   │   │   s.append(f'{script.title()}:{round(time.time()-t0, 2)}s')                                      │
│                                                                                                                      │
│ D:\automatic\extensions\unprompted\scripts\unprompted.py:649 in process_batch                                        │
│                                                                                                                      │
│   648 │   │   │   else:                                                                                              │
│ ❱ 649 │   │   │   │   prompt_result = Unprompted.shortcode_user_vars["prompt"]                                       │
│   650 │   │   │   │   negative_prompt_result = Unprompted.shortcode_user_vars["negative_prompt                       │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
KeyError: 'prompt'
100%|██████████████████████████████████████████████████████████████████████████████████| 40/40 [00:04<00:00,  8.02it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 40/40 [00:08<00:00,  4.48it/s]
13:01:44-000619 ERROR    Running script process: D:\automatic\extensions\unprompted\scripts\unprompted.py:
                         AttributeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\automatic\modules\scripts.py:406 in process                                                                       │
│                                                                                                                      │
│   405 │   │   │   │   args = p.per_script_args.get(script.title(), p.script_args[script.args_f                       │
│ ❱ 406 │   │   │   │   script.process(p, *args, **kwargs)                                                             │
│   407 │   │   │   │   s.append(f'{script.title()}:{round(time.time()-t0, 2)}s')                                      │
│                                                                                                                      │
│ D:\automatic\extensions\unprompted\scripts\unprompted.py:565 in process                                              │
│                                                                                                                      │
│   564 │   │   if sd_models.model_data.sd_model:                                                                      │
│ ❱ 565 │   │   │   if sd_models.model_data.sd_model.is_sdxl: Unprompted.shortcode_user_vars["sd                       │
│   566 │   │   │   elif sd_models.model_data.sd_model.is_sd2: Unprompted.shortcode_user_vars["s                       │
│                                                                                                                      │
│ D:\automatic\venv\lib\site-packages\torch\nn\modules\module.py:1614 in __getattr__                                   │
│                                                                                                                      │
│   1613 │   │   │   │   return modules[name]                                                                          │
│ ❱ 1614 │   │   raise AttributeError("'{}' object has no attribute '{}'".format(                                      │
│   1615 │   │   │   type(self).__name__, name))                                                                       │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'LatentDiffusion' object has no attribute 'is_sdxl'
13:01:44-095124 ERROR    Running script process batch: D:\automatic\extensions\unprompted\scripts\unprompted.py:
                         KeyError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\automatic\modules\scripts.py:430 in process_batch                                                                 │
│                                                                                                                      │
│   429 │   │   │   │   args = p.per_script_args.get(script.title(), p.script_args[script.args_f                       │
│ ❱ 430 │   │   │   │   script.process_batch(p, *args, **kwargs)                                                       │
│   431 │   │   │   │   s.append(f'{script.title()}:{round(time.time()-t0, 2)}s')                                      │
│                                                                                                                      │
│ D:\automatic\extensions\unprompted\scripts\unprompted.py:649 in process_batch                                        │
│                                                                                                                      │
│   648 │   │   │   else:                                                                                              │
│ ❱ 649 │   │   │   │   prompt_result = Unprompted.shortcode_user_vars["prompt"]                                       │
│   650 │   │   │   │   negative_prompt_result = Unprompted.shortcode_user_vars["negative_prompt                       │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
KeyError: 'prompt'
100%|██████████████████████████████████████████████████████████████████████████████████| 40/40 [00:03<00:00, 11.81it/s]
13:02:03-924015 INFO     UI defaults saved: D:\automatic\ui-config.json
13:02:12-040009 ERROR    Running script process: D:\automatic\extensions\unprompted\scripts\unprompted.py:
                         AttributeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\automatic\modules\scripts.py:406 in process                                                                       │
│                                                                                                                      │
│   405 │   │   │   │   args = p.per_script_args.get(script.title(), p.script_args[script.args_f                       │
│ ❱ 406 │   │   │   │   script.process(p, *args, **kwargs)                                                             │
│   407 │   │   │   │   s.append(f'{script.title()}:{round(time.time()-t0, 2)}s')                                      │
│                                                                                                                      │
│ D:\automatic\extensions\unprompted\scripts\unprompted.py:565 in process                                              │
│                                                                                                                      │
│   564 │   │   if sd_models.model_data.sd_model:                                                                      │
│ ❱ 565 │   │   │   if sd_models.model_data.sd_model.is_sdxl: Unprompted.shortcode_user_vars["sd                       │
│   566 │   │   │   elif sd_models.model_data.sd_model.is_sd2: Unprompted.shortcode_user_vars["s                       │
│                                                                                                                      │
│ D:\automatic\venv\lib\site-packages\torch\nn\modules\module.py:1614 in __getattr__                                   │
│                                                                                                                      │
│   1613 │   │   │   │   return modules[name]                                                                          │
│ ❱ 1614 │   │   raise AttributeError("'{}' object has no attribute '{}'".format(                                      │
│   1615 │   │   │   type(self).__name__, name))                                                                       │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'LatentDiffusion' object has no attribute 'is_sdxl'
13:02:12-134561 ERROR    Running script process batch: D:\automatic\extensions\unprompted\scripts\unprompted.py:
                         KeyError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\automatic\modules\scripts.py:430 in process_batch                                                                 │
│                                                                                                                      │
│   429 │   │   │   │   args = p.per_script_args.get(script.title(), p.script_args[script.args_f                       │
│ ❱ 430 │   │   │   │   script.process_batch(p, *args, **kwargs)                                                       │
│   431 │   │   │   │   s.append(f'{script.title()}:{round(time.time()-t0, 2)}s')                                      │
│                                                                                                                      │
│ D:\automatic\extensions\unprompted\scripts\unprompted.py:649 in process_batch                                        │
│                                                                                                                      │
│   648 │   │   │   else:                                                                                              │
│ ❱ 649 │   │   │   │   prompt_result = Unprompted.shortcode_user_vars["prompt"]                                       │
│   650 │   │   │   │   negative_prompt_result = Unprompted.shortcode_user_vars["negative_prompt                       │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
KeyError: 'prompt'`

**Comment by mokumoku4865** [comment]
13:01:16-441720 ERROR    Running script process: D:\automatic\extensions\unprompted\scripts\unprompted.py:
                         AttributeError
 Traceback (most recent call last) 
 D:\automatic\modules\scripts.py:406 in process                                                                       
                                                                                                                      
   405             args = p.per_script_args.get(script.title(), p.script_args[script.args_f                       
 ❱ 406             script.process(p, *args, **kwargs)                                                             
   407             s.append(f'{script.title()}:{round(time.time()-t0, 2)}s')                                      
                                                                                                                      
 D:\automatic\extensions\unprompted\scripts\unprompted.py:565 in process                                              
                                                                                                                      
   564       if sd_models.model_data.sd_model:                                                                      
 ❱ 565          if sd_models.model_data.sd_model.is_sdxl: Unprompted.shortcode_user_vars["sd                       
   566          elif sd_models.model_data.sd_model.is_sd2: Unprompted.shortcode_user_vars["s                       
                                                                                                                      
 D:\automatic\venv\lib\site-packages\torch\nn\modules\module.py:1614 in __getattr__                                   
                                                                                                                      
   1613             return modules[name]                                                                          
 ❱ 1614       raise AttributeError("'{}' object has no attribute '{}'".format(                                      
   1615          type(self).__name__, name))                                                                       

AttributeError: 'LatentDiffusion' object has no attribute 'is_sdxl'
Loading weights: D:\automatic\models\Lora\add_detail.safetensors ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/37.9 MB -:--:--
Loading weights: D:\automatic\models\Lora\flat2.safetensors ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/6.9 MB -:--:--
13:01:16-770895 ERROR    Running script process batch: D:\automatic\extensions\unprompted\scripts\unprompted.py:
                         KeyError
 Traceback (most recent call last) 
 D:\automatic\modules\scripts.py:430 in process_batch                                                                 
                                                                                                                      
   429             args = p.per_script_args.get(script.title(), p.script_args[script.args_f                       
 ❱ 430             script.process_batch(p, *args, **kwargs)                                                       
   431             s.append(f'{script.title()}:{round(time.time()-t0, 2)}s')                                      
                                                                                                                      
 D:\automatic\extensions\unprompted\scripts\unprompted.py:649 in process_batch                                        
                                                                                                                      
   648          else:                                                                                              
 ❱ 649             prompt_result = Unprompted.shortcode_user_vars["prompt"]                                       
   650             negative_prompt_result = Unprompted.shortcode_user_vars["negative_prompt                       

KeyError: 'prompt'
100%|██████████████████████████████████████████████████████████████████████████████████| 40/40 [00:04<00:00,  8.02it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 40/40 [00:08<00:00,  4.48it/s]
13:01:44-000619 ERROR    Running script process: D:\automatic\extensions\unprompted\scripts\unprompted.py:
                         AttributeError
 Traceback (most recent call last) 
 D:\automatic\modules\scripts.py:406 in process                                                                       
                                                                                                                      
   405             args = p.per_script_args.get(script.title(), p.script_args[script.args_f                       
 ❱ 406             script.process(p, *args, **kwargs)                                                             
   407             s.append(f'{script.title()}:{round(time.time()-t0, 2)}s')                                      
                                                                                                                      
 D:\automatic\extensions\unprompted\scripts\unprompted.py:565 in process                                              
                                                                                                                      
   564       if sd_models.model_data.sd_model:                                                                      
 ❱ 565          if sd_models.model_data.sd_model.is_sdxl: Unprompted.shortcode_user_vars["sd                       
   566          elif sd_models.model_data.sd_model.is_sd2: Unprompted.shortcode_user_vars["s                       
                                                                                                                      
 D:\automatic\venv\lib\site-packages\torch\nn\modules\module.py:1614 in __getattr__                                   
                                                                                                                      
   1613             return modules[name]                                                                          
 ❱ 1614       raise AttributeError("'{}' object has no attribute '{}'".format(                                      
   1615          type(self).__name__, name))                                                                       

AttributeError: 'LatentDiffusion' object has no attribute 'is_sdxl'
13:01:44-095124 ERROR    Running script process batch: D:\automatic\extensions\unprompted\scripts\unprompted.py:
                         KeyError
 Traceback (most recent call last) 
 D:\automatic\modules\scripts.py:430 in process_batch                                                                 
                                                                                                                      
   429             args = p.per_script_args.get(script.title(), p.script_args[script.args_f                       
 ❱ 430             script.process_batch(p, *args, **kwargs)                                                       
   431             s.append(f'{script.title()}:{round(time.time()-t0, 2)}s')                                      
                                                                                                                      
 D:\automatic\extensions\unprompted\scripts\unprompted.py:649 in process_batch                                        
                                                                                                                      
   648          else:                                                                                              
 ❱ 649             prompt_result = Unprompted.shortcode_user_vars["prompt"]                                       
   650             negative_prompt_result = Unprompted.shortcode_user_vars["negative_prompt                       

KeyError: 'prompt'
100%|██████████████████████████████████████████████████████████████████████████████████| 40/40 [00:03<00:00, 11.81it/s]
13:02:03-924015 INFO     UI defaults saved: D:\automatic\ui-config.json
13:02:12-040009 ERROR    Running script process: D:\automatic\extensions\unprompted\scripts\unprompted.py:
                         AttributeError
 Traceback (most recent call last) 
 D:\automatic\modules\scripts.py:406 in process                                                                       
                                                                                                                      
   405             args = p.per_script_args.get(script.title(), p.script_args[script.args_f                       
 ❱ 406             script.process(p, *args, **kwargs)                                                             
   407             s.append(f'{script.title()}:{round(time.time()-t0, 2)}s')                                      
                                                                                                                      
 D:\automatic\extensions\unprompted\scripts\unprompted.py:565 in process                                              
                                                                                                                      
   564       if sd_models.model_data.sd_model:                                                                      
 ❱ 565          if sd_models.model_data.sd_model.is_sdxl: Unprompted.shortcode_user_vars["sd                       
   566          elif sd_models.model_data.sd_model.is_sd2: Unprompted.shortcode_user_vars["s                       
                                                                                                                      
 D:\automatic\venv\lib\site-packages\torch\nn\modules\module.py:1614 in __getattr__                                   
                                                                                                                      
   1613             return modules[name]                                                                          
 ❱ 1614       raise AttributeError("'{}' object has no attribute '{}'".format(                                      
   1615          type(self).__name__, name))                                                                       

AttributeError: 'LatentDiffusion' object has no attribute 'is_sdxl'
13:02:12-134561 ERROR    Running script process batch: D:\automatic\extensions\unprompted\scripts\unprompted.py:
                         KeyError
 Traceback (most recent call last) 
 D:\automatic\modules\scripts.py:430 in process_batch                                                                 
                                                                                                                      
   429             args = p.per_script_args.get(script.title(), p.script_args[script.args_f                       
 ❱ 430             script.process_batch(p, *args, **kwargs)                                                       
   431             s.append(f'{script.title()}:{round(time.time()-t0, 2)}s')                                      
                                                                                                                      
 D:\automatic\extensions\unprompted\scripts\unprompted.py:649 in process_batch                                        
                                                                                                                      
   648          else:                                                                                              
 ❱ 649             prompt_result = Unprompted.shortcode_user_vars["prompt"]                                       
   650             negative_prompt_result = Unprompted.shortcode_user_vars["negative_prompt                       

KeyError: 'prompt'

**Comment by ThereforeGames** [comment]
Hi @kouta3619,

Thank you for reaching out.

At a glance, this appears to be related to SD.Next not supporting the `is_sdxl`, `is_sd1` and `is_sd2` variables that are present in the A1111 WebUI.

I have implemented a possible workaround, but since Vlad's fork is becoming more distinct/opinionated as time goes on, I cannot guarantee that it will continue working with Unprompted - I am only supporting Automatic's WebUI at this time.

That said, feel free to give the hotfix a try and let me know if it makes a difference for you.
