### ISSUE TITLE
highres fix doesn't work with sdxl

### ISSUE THREAD

**Issue by magicbot42** [ThereforeGames/unprompted#178]
Hi again, 

Just playing around with sdxl dreamshaper from civitai and noticed that with only umprompted enabled, highres fix errors out with these sdxl models.  This is with the latest 1.5.1 version of automatic1111.   Was suprised that unprompted already worked with sdxl otherwise though.

Cheers!

**Comment by ThereforeGames** [comment]
> Was suprised that unprompted already worked with sdxl otherwise though.

Me too... :-)

I'm taking a look at the issue now and will try to have a fix out soon.

**Comment by ThereforeGames** [comment]
Hmm, I'm actually not seeing any errors using hr fix with the model you mentioned. I'm trying with "dreamshaperXL09Alpha_alpha2Xl10.safetensors [0f1b80cfe8]."

Can you share your console log with me? It might also be helpful to know what your hr fix settings are - I tested Latent upscaler with 0.5 denoising and 1.5x upscale.

Thanks!

**Comment by magicbot42** [comment]
So the Traceback only seems to occur when reading the prompt from within a file.  Here i've put a simple prompt in x/test.txt and negative prompt in x/test_negative.txt.  The prompt/negative prompt work with hires fix when outside of the files and without the file shortcode calling them, but once inside the files and calling them with the file shortcode I get this traceback: 

![image](https://github.com/ThereforeGames/unprompted/assets/3104806/08e301ae-67bf-4156-8684-761401646e92)

These are my current versions, plus umprompted is the latest version.  only unprompted enabled:

![image](https://github.com/ThereforeGames/unprompted/assets/3104806/0eec9680-b80a-4509-bf2a-80b64cdc88df)

Maybe this is a similar error to the other one recently seen with hires fix?

**Comment by magicbot42** [comment]
Also, forgot to mention, here I used the same settings with Latent upscaler as you used .5 denoise, and 1.5 scale.   It seems to be the call to the file shortcode causing hires fix to tracback like this.

**Comment by magicbot42** [comment]
Actually after playing around, I'm not sure I know what's going on here.   It seems somewhat intermittent.  Not always caused by hires fix being on, but easier for it to happen with it on.  It doesn't happen with unprompted turned off.  Quick google and it seems other extensions are causing this too with sdxl: 
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/12038
and here in the comments: 
https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/11757

**Comment by Kadah** [comment]
Update ControlNets extension, it should be fixed now. Update or disable any other extensions that hook in to gen.

**Comment by ThereforeGames** [comment]
It turns out that hires pass with SDXL models refer to `hr_prompts` instead of `all_hr_prompts`... I'm not sure if the latter is deprecated everywhere, or just for SDXL. Either way, I'll have a fix for you out momentarily.

**Comment by ThereforeGames** [comment]
Fix is out. Please let me know if hires fix still gives you any trouble.
