### ISSUE TITLE
right is less than left problem tx2tmask

### ISSUE THREAD

**Issue by Someonetoldme584** [ThereforeGames/unprompted#179]

**Comment by ThereforeGames** [comment]
Hi @Someonetoldme584,

Can you share your console log to help me diagnose the problem?

Thank you!

**Comment by Someonetoldme584** [comment]
![image](https://github.com/ThereforeGames/unprompted/assets/79592731/78515f43-5f4e-49e6-9798-90eac7ebb36f)

**Comment by ThereforeGames** [comment]
Hi @Someonetoldme584,

I need to see the log output from the txt2mask shortcode - it's likely further up than the messages in your screenshot.

Additionally, it would be helpful to know the following:

- What are your prompt and inference settings?
- Are you using any other extensions, and if so have you tried disabling them?
- Are both Unprompted and the WebUI up-to-date?

Thank you!

**Comment by ThereforeGames** [comment]
Close due to lack of activity. Feel free to re-open this issue if the problem persists. Thank you!
