### ISSUE TITLE
Permit user to change the "|" choose separator & question on tag delimiters.

### ISSUE THREAD

**Issue by valconius** [ThereforeGames/unprompted#18]
Actually I already did this and it works but I don't know how to submit a pull request or use anything more complicated than git branch git fetch git checkout git commit and that's about it. Help would be appreciated in that regard!

Objective: Before the following, we cannot use webui's prompt alternation feature. The following should only choose between two options, `river` and `[magma|river]`: `[choose]river|[magma|river][/choose]`. We solve this by using ¦ instead of | for unprompted's stuff.

Step 1. Add a new setting to `unprompted/config.json`: `{ … "syntax": { "choose_sep":"|", … }, … }`

Step 2. It seems the separator is only ever used in one file, so change `unprompted/shortcodes/basic/choose.py:9` to: `parts = content.replace(self.Unprompted.Config.syntax.n_temp,self.Unprompted.Config.syntax.choose_sep).split(self.Unprompted.Config.syntax.choose_sep)`

Elaboration: The webui's "alternating prompt" syntax uses the pipe character between brackets, and the more elaborate forms of prompt weighing as in webui's PR#1273 go even more over-the-top with pipe character usage. I use the EURKEY keyboard layout so C-S-| gives me the unicode ¦ character very easily, permitting me to shut off my brain and not think about anything else.

Aside: In practice, I also change the tag delimiter syntax things to beg:« end:» altbeg:‹ altend:› so that I don't have to bother thinking about when unprompted's syntax might clash with some extension's or webui's syntaxes. However, this would cause horrible problems if I used other people's template files. Is it possible to specify tag delimiters and other syntax rules at the very top of a file? For example, in emacs a line usually exists like `# -*- var: 1; rule: (eval 2); constraint; -*-` in the first three lines of a file to provide file-local variables to control things like indentation or syntax highlighting.

**Comment by ThereforeGames** [comment]
Hi @valconius,

Thank you for such a thoughtful post!

You bring up a good point about `|` conflicting with the WebUI's alternating prompt feature - I will certainly implement the ability to change this character via config.json. However, I'm not sure if `¦` is the ideal candidate (I thought I had dust on my screen when I first saw it in your post, lol). It's difficult to choose the right syntax sometimes.

Maybe others can chime in with their thoughts... **what's the best character for the [choose] delimiter that doesn't conflict with the WebUI?**

As for your second question:

> Is it possible to specify tag delimiters and other syntax rules at the very top of a file? For example, in emacs a line usually exists like # -*- var: 1; rule: (eval 2); constraint; -*- in the first three lines of a file to provide file-local variables to control things like indentation or syntax highlighting.

Yeah, that's a great idea. I was actually thinking about creating a shortcode that would overwrite config.json - ideally, you would be able to use it to point to another json file or just write your new settings inline. Would be tremendously useful for sharing templates without worrying about the receiving party's config.

I'm not the best person to ask about creating PRs, I'm pretty new to Github's ecosystem myself :)

**Comment by ThereforeGames** [comment]
Hi @valconius,

Just released a new version of Unprompted with some of your suggestions!

The `[choose]` delimiter is now declared in the config as `shortcodes.choose_delimiter`. It still defaults to `|` for the time being.

You can also use the new `[config]` shortcode to override your settings on a per-template basis.

It accepts both inline JSON and external file paths. You can do something like this at the top of your template:

```
[config]{"shortcodes":{"choose_delimiter":"¦"}}[/config]
```

I hope that helps. Let me know if you have any questions!
