### ISSUE TITLE
[set]some value[/set] always displays it's value to the prompt?

### ISSUE THREAD

**Issue by magicbot42** [ThereforeGames/unprompted#183]
Unless I'm missing something, it seems this is the case. 

Can we have a _hidden option for the [set] shortcode such that the contents (value] of the between the shortcode brackets isn't immediately echod to the prompt.  Sometimes I just want to set a variable and not have the value inside of [set somevariable]value[/set] echo'd to the prompt until I use the [get somvariable] shortcode to retrieve that value.

Maybe hidden is not the best name but some optoin to not have the contents of set reflected in the prompt when set would be nice.

**Comment by ThereforeGames** [comment]
Hi @magicbot42,

Unless there's a bug I'm not aware of, the `[set]` shortcode should not echo back to the prompt. Here's a Dry Run test:

![image](https://github.com/ThereforeGames/unprompted/assets/95403634/40af684b-ad9f-4eb2-8757-1d43a332e80d)

In fact, you need to use the `_out` parg if you want to print the set content.

May I see the code that's giving you trouble? Thanks.

**Comment by magicbot42** [comment]
Oh wow, I've just been misunderstanding the use of the _out option this whole time.
This is a non issue then.. Sorry about that.

BTW, can confirm the fix for the hires fix is working with sdxl as well.  Thanks for that!

**Comment by magicbot42** [comment]
Closing as is a non-issue
