### ISSUE TITLE
[get a _default=1] gives error

### ISSUE THREAD

**Issue by ChieVFX** [ThereforeGames/unprompted#185]
Apparently, "_default" tag only works for string values.
When I haven't set a variable and I do this:
```[get a _default="yellow"]```
it gives me "yellow" as expected.

However, any of these
```[get a _default=1]```
```[get a _default=0.6]```
```[get a _default=1_0]```
will all produce error instead of result. :(

**Comment by ThereforeGames** [comment]
Hi @ChieVFX,

Thanks for bringing this to my attention! I have fixed it internally and will release it as part of a big patch later today.

**Comment by ThereforeGames** [comment]
Fixed in Unprompted v9.14.0.
