### ISSUE TITLE
[file a some_var=1] not overriding variable

### ISSUE THREAD

**Issue by ChieVFX** [ThereforeGames/unprompted#186]
Let's say I have a file "a.txt" with this inside:
```
[sets some_var=2]
[get some_var]
```

If I call
```[file a some_var=7]```
the result will be "2".

So, if a variable is set inside a file (either through "sets" or "set" shortcode), the file's parameters get ignored.

The only way I was able to get it sorta working is through using "_default".
E.g., if the "a.txt" is this:
```[get some_var _default="yellow"]```
then calling for ```[file a some_var="red"]``` will give me "red" as expected.
Unfortunately, this means I can't use "if" shortcodes, since they don't support _default.
And "_default" only supports string values, so that is also not working 100% right.

**Comment by ChieVFX** [comment]
Update: using "_new" keyword in the "[set]" shortcode actually fixes this issue.
So,
```
[sets some_var=2 _new]
[get some_var]
```
with the call ```[file a some_var="8"]```
gives the correct "8" as result

So, I think the logic is inverted in the "_new".

Or is it indended? Wasn't able to understand the intention from the docs. But, fortunately, this works out for me.

**Comment by ThereforeGames** [comment]
Hi @ChieVFX,

Yes, this sounds like the intended behavior.

The `_new` flag bypasses the `[set(s)]` block if the named variable already exists. In your case, `some_var` was instantiated when `[file]` was called.

It's "new" as in, _"set this only if it's new."_

I'll take a look at the manual to see if I can improve the wording. Thanks.

**Comment by ThereforeGames** [comment]
Documentation improved in v9.15.0.
