### ISSUE TITLE
img2img_autosize shortscript broken with 1.6

### ISSUE THREAD

**Issue by R-Ladig** [ThereforeGames/unprompted#195]
### Due diligence

- [X] I checked for similar issues and couldn't find any.
- [X] My WebUI and Unprompted are both up-to-date.
- [X] I disabled my other extensions but the problem persists.

### Describe the bug

Just tried it with a new install to confirm. Many of the .py shortscripts are broken with AUTOMATIC1111 1.6. 

E.g. img2img_autosize will output: 
*** Error completing request
*** Arguments: ('task(02xofa2rc0ts9eo)', 0, '', '', [], <PIL.Image.Image image mode=RGBA size=1500x1000 at 0x21DC2483DC0>, None, None, None, None, None, None, 20, 'DPM++ 2M Karras', 4, 0, 1, 1, 1, 7, 1.5, 0.75, 0, 512, 512, 1, 0, 0, 32, 0, '', '', '', [], False, [], '', <gradio.routes.Request object at 0x0000021DC24BE0E0>, 0, False, '', 0.8, -1, False, -1, 0, 0, 0, True, -1.0, True, '* `CFG Scale` should be 2 or lower.', True, True, '', '', True, 50, True, 1, 0, False, 4, 0.5, 'Linear', 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "D:\SD\stable-diffusion-webui-master\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "D:\SD\stable-diffusion-webui-master\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "D:\SD\stable-diffusion-webui-master\modules\img2img.py", line 208, in img2img
        processed = process_images(p)
      File "D:\SD\stable-diffusion-webui-master\modules\processing.py", line 732, in process_images
        res = process_images_inner(p)
      File "D:\SD\stable-diffusion-webui-master\modules\processing.py", line 803, in process_images_inner
        p.init(p.all_prompts, p.all_seeds, p.all_subseeds)
      File "D:\SD\stable-diffusion-webui-master\modules\processing.py", line 1451, in init
        image = images.resize_image(self.resize_mode, image, self.width, self.height)
      File "D:\SD\stable-diffusion-webui-master\modules\images.py", line 281, in resize_image
        res = resize(im, width, height)
      File "D:\SD\stable-diffusion-webui-master\modules\images.py", line 261, in resize
        return im.resize((w, h), resample=LANCZOS)
      File "D:\SD\stable-diffusion-webui-master\venv\lib\site-packages\PIL\Image.py", line 2193, in resize
        return self._new(self.im.resize(size, resample, box))
    TypeError: 'float' object cannot be interpreted as an integer

Any ideas how to fix?

### Unprompted version

15da148b

### WebUI version

1.6

**Comment by ThereforeGames** [comment]
Hi @R-Ladig,

The `[img2img_autosize]` shortcode appears to be working correctly on my device - could you give me an example prompt to help me reproduce the issue, as well as the dimensions of the original image?

Also, I don't see anything in your log that refers to Unprompted. It looks like the error is happening with the WebUI's images.py module when it calls the PIL library. Have you tried rebuilding your `venv` folder? (I assume this is what you meant by new install, but I figured it wouldn't hurt to ask.)

**Comment by R-Ladig** [comment]
Hi thanks for checking. 

Just confirmed again: 
- New, empty folder
- Clone Automatic 1.6.0.
- start via webui-user.bat
- let it download all dependencies (plus default model v1-5-pruned-emaonly.safetensors)
- install unprompted via extension tab
- full restart (kill process, close browser)
- used a random image on the internet in img2img (https://picsum.photos/200/300)
- promt: test - neg prompt: no test
- enable unprompted, wizard, shortcodes, img2img_autosize, check in Auto-include this in prompt, leave size at default 512
-  get error as above 

I noticed that I am using Python 3.10.6, but in Automatic 1.5.x. everything worked just fine, so, I'm not sure this is it.


ERROR LOG:
*** Error completing request
*** Arguments: ('task(q2sebln5td9la4d)', 0, 'test', 'no test', [], <PIL.Image.Image image mode=RGBA size=536x354 at 0x2786DC79150>, None, None, None, None, None, None, 20, 'DPM++ 2M Karras', 4, 0, 1, 1, 1, 7, 1.5, 0.75, 0, 512, 512, 1, 0, 0, 32, 0, '', '', '', [], False, [], '', <gradio.routes.Request object at 0x0000027869521F90>, 0, False, '', 0.8, -1, False, -1, 0, 0, 0, True, -1.0, True, '* `CFG Scale` should be 2 or lower.', True, True, '', '', True, 50, True, 1, 0, False, 4, 0.5, 'Linear', 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "D:\SD\stable-diffusion-webui-1.6.0\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "D:\SD\stable-diffusion-webui-1.6.0\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "D:\SD\stable-diffusion-webui-1.6.0\modules\img2img.py", line 208, in img2img
        processed = process_images(p)
      File "D:\SD\stable-diffusion-webui-1.6.0\modules\processing.py", line 732, in process_images
        res = process_images_inner(p)
      File "D:\SD\stable-diffusion-webui-1.6.0\modules\processing.py", line 803, in process_images_inner
        p.init(p.all_prompts, p.all_seeds, p.all_subseeds)
      File "D:\SD\stable-diffusion-webui-1.6.0\modules\processing.py", line 1451, in init
        image = images.resize_image(self.resize_mode, image, self.width, self.height)
      File "D:\SD\stable-diffusion-webui-1.6.0\modules\images.py", line 281, in resize_image
        res = resize(im, width, height)
      File "D:\SD\stable-diffusion-webui-1.6.0\modules\images.py", line 261, in resize
        return im.resize((w, h), resample=LANCZOS)
      File "D:\SD\stable-diffusion-webui-1.6.0\venv\lib\site-packages\PIL\Image.py", line 2193, in resize
        return self._new(self.im.resize(size, resample, box))
    TypeError: 'float' object cannot be interpreted as an integer

---

**Comment by ThereforeGames** [comment]
Hi @R-Ladig,

Thank you for clarifying - I can confirm that this error occurs specifically when auto-including the shortcode via the Wizard.

I have fixed the issue internally but it will be a while before I push the next Unprompted patch. Here are two solutions you can use in the meantime:

1. Manually add `[img2img_autosize]` to your prompts instead of using the Wizard.
2. Download the modified img2img_autosize.py and place it in `unprompted/shortcodes/stable_diffusion`, then restart the WebUI and try the Wizard again:

[img2img_autosize.zip](https://github.com/ThereforeGames/unprompted/files/12589630/img2img_autosize.zip)

You also mentioned that many other shortcodes were giving you trouble - could you tell me more about that? Thanks!

**Comment by ThereforeGames** [comment]
Fixed `[img2img_autosize]` in v10.0.0.
