### ISSUE TITLE
Negative prompt is not working after today's automatic update

### ISSUE THREAD

**Issue by aniketgore** [ThereforeGames/unprompted#20]
set negative_prompt has stopped working after today's automatic update. Other set options like cfg and stuff works.

**Comment by strangePause** [comment]
Same here.

**Comment by strangePause** [comment]
Also, to add, while manually typing the location of the negative prompt file, it reads it as a regular prompt. I have made sure that it is the correct file name/location that it belongs to.
https://imgur.com/a/uoNULK4

**Comment by aniketgore** [comment]
After today's update the recursive read from the folders is not working. Like we could use /clothes/* and it would pick randomly from all the files inside /clothes/ folder. But now it can't.

**Comment by ThereforeGames** [comment]
Hi, a new update has been released that fixes `negative_prompt` (v0.9.0).

> After today's update the recursive read from the folders is not working. Like we could use /clothes/* and it would pick randomly from all the files inside /clothes/ folder. But now it can't.

That's odd - the wildcard appears to be working correctly with `[file]` on my end, e.g. `[files clothes/*]` will pick something at random within the clothes directory.

Are there any errors in your command prompt?

**Comment by aniketgore** [comment]
> Hi, a new update has been released that fixes `negative_prompt` (v0.9.0).
> 
> > After today's update the recursive read from the folders is not working. Like we could use /clothes/* and it would pick randomly from all the files inside /clothes/ folder. But now it can't.
> 
> That's odd - the wildcard appears to be working correctly with `[file]` on my end, e.g. `[files clothes/*]` will pick something at random within the clothes directory.
> 
> Are there any errors in your command prompt?
Thanks for the update. Really appreciate your help. This tool is a daily driver for my SD adventures these days :)
I will check in sometime and let you know. I had the issue when the 2.0 model was loaded. It said something like file attribute not found or some error. Will get a screenshot for you after updating my extension.

**Comment by ThereforeGames** [comment]
Sounds good, thanks! Glad you're liking the extension.

I'm going to mark this issue as closed, but feel free to open another if the wildcard problem comes up again.

**Comment by reserved-word** [comment]
@ThereforeGames Hi, it looks like the extension is ignoring negative prompts from styles.
**Without** Unprompted: result negative prompt = **"main" negative prompt + negative styles prompts**
**With** Unprompted: result negative prompt = **"main" negative prompt**

(positive style prompts work properly)
