### ISSUE TITLE
Encoding problem with icons

### ISSUE THREAD

**Issue by ghost** [ThereforeGames/unprompted#202]
### Due diligence

- [X] I checked for similar issues and couldn't find any.
- [X] My WebUI and Unprompted are both up-to-date.
- [X] I disabled my other extensions but the problem persists.

### Describe the bug

Hello, I am trying to use your extension.

On Unprompted template editor, when I click on common/examples/bodysnapcher.txt or regional_prompter_buddy.txt on the extension

I receive a decode error :

 File "D:\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f

The problem seems to be icons, if I remove them, there's no problem.

I am using Windows 11 Pro French

### Unprompted version

9.16.1

### WebUI version

1.6.0

**Comment by ThereforeGames** [comment]
Hi @jvachez,

Thank you for reaching out! The Template Editor is now able to parse emojis in v10.1.0.
