### ISSUE TITLE
Getting Error with Unprompted and Randomize

### ISSUE THREAD

**Issue by dtlnor** [ThereforeGames/unprompted#21]
if I enabled both unprompted and [randomize](https://github.com/stysmmaker/stable-diffusion-webui-randomize) extension,
I am not able to do img2img. It always has zero iteration on whatever denoise strength I set. 
This is very werid as randomize should do nothing on img2img.

webui: 828438b4a190759807f9054932cae3a8b880ddf1
Unprompted: 76860e69a174095adfa32ce61a0b1e408e15660a
randomize: 1da87513c0f63c109f939a169d48c78f2451d948

**Comment by ThereforeGames** [comment]
Hi @dtlnor,

I'm going through old issues that I overlooked. Unfortunately, the randomize extension no longer exists on GitHub so I'm marking this as closed. Feel free to let me know if you think this still requires my attention. Thank you!
