### ISSUE TITLE
Broken interaction between prompt, hires fix and batch count

### ISSUE THREAD

**Issue by entusiastaIA** [ThereforeGames/unprompted#210]
### Due diligence

- [X] I checked for similar issues and couldn't find any.
- [X] My WebUI and Unprompted are both up-to-date.
- [X] I disabled my other extensions but the problem persists.

### Describe the bug

While using complex inizialization prompts generated by the wizard, such as this:

[call 'common\functions\Aine-MP' stability=all reality=all subject=all age=all nsfw=all camera=all distance=all race=all haircolor=all haircut=all subjectboolean=0 personageboolean=0 appearanceboolean=0 attractiveboolean=0 complexionboolean=0 bodyshapeboolean=0 fleshboolean=0 extraboolean=0 faceboolean=0 haircolorboolean=0 haircutboolean=0 raceboolean=0 poseboolean=0 qualityboolean=0 lightingboolean=0 workboolean=0 cameraboolean=0 photographersboolean=0 backgroundsboolean=0 negative_promptboolean=0 name='AIne Captain's Master Prompt']

(They obviously call files which call files which call files...)

If they are used with any batch count and NO hires fix. they work perfectly fine.
If they are used with batch count = 1 AND hires fix. they work perfectly fine.
If they are used with batch count > 1 AND hires fix. they break.

They break means exactly this:
The first image is processed with the proper prompt  on the first pass, but for the hires fix pass it instead uses the unprompted raw code, such as if I had used "" in the short code. For example lets say that "[call 'common\functions\Aine-MP' ... subject=all ... ]" resulted in "a woman". Then the first image would be generated the same as if I had writen this WITHOUT unprompted:
prompt: a woman.
hires fix prompt: [call 'common\functions\Aine-MP' ... subject=all ... ] <- As if I had written those symbols and words, without processing them.

Examples. Raw 512x512 image:
![927807304-512x512-20231026_233036_359885](https://github.com/ThereforeGames/unprompted/assets/113212323/6833d341-54de-4ce7-be2f-849bd9fc9d05)

512x512 image with batch count = 2:
![927807304-512x512-20231026_233141_936580](https://github.com/ThereforeGames/unprompted/assets/113212323/11800b35-8ee1-4ab8-8789-f18111ff9301)

1024x1024 image after hires fix and batch count = 1:
![927807304-1024x1024-20231026_233247_425308](https://github.com/ThereforeGames/unprompted/assets/113212323/a7eba3d4-80c8-4246-8fb4-5a90dbdc38ff)

1024x1024 image after hires fix and batch count > 1:
![927807304-1024x1024-20231026_233353_716568](https://github.com/ThereforeGames/unprompted/assets/113212323/994aa3ae-ec24-462d-bab4-6753d1b1484b)

Then, after this already broken image, the console errors and nothing else gets processed:

![Captura](https://github.com/ThereforeGames/unprompted/assets/113212323/4e9d6be7-b157-4f10-b012-6d9b480c90de)

The bug is new, I have been using it on old versions with these same files without trouble, then after updating both A1111 and unprompted it started happening. The only change I made was updating [file] to [call] in my code, but I tested it with [file] too and the same happens. It's a brand new installation, only A1111, unprompted and my template for unprompted.

Thank you for your time. I wish I could narrow it further, but I don't know what else could be involved.

### Log output

```shell
*** Error completing request
*** Arguments: ('task(xfaw0su8kpcrkdu)', "[call 'common\\functions\\Aine-MP' stability=all reality=all subject=all age=all nsfw=all camera=all distance=all race=all haircolor=all haircut=all subjectboolean=0 personageboolean=0 appearanceboolean=0 attractiveboolean=0 complexionboolean=0 bodyshapeboolean=0 fleshboolean=0 extraboolean=0 faceboolean=0 haircolorboolean=0 haircutboolean=0 raceboolean=0 poseboolean=0 qualityboolean=0 lightingboolean=0 workboolean=0 cameraboolean=0 photographersboolean=0 backgroundsboolean=0 negative_promptboolean=0 name='AIne Captain's Master Prompt']", '', [], 20, 'DPM++ 2M Karras', 2, 1, 7, 512, 512, True, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], <gradio.routes.Request object at 0x000002D57602A110>, 0, False, '', 0.8, 927807304, False, -1, 0, 0, 0, True, -1.0, True, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "L:\AI\stable-diffusion-webui-master\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "L:\AI\stable-diffusion-webui-master\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "L:\AI\stable-diffusion-webui-master\modules\txt2img.py", line 55, in txt2img
        processed = processing.process_images(p)
      File "L:\AI\stable-diffusion-webui-master\modules\processing.py", line 732, in process_images
        res = process_images_inner(p)
      File "L:\AI\stable-diffusion-webui-master\modules\processing.py", line 867, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "L:\AI\stable-diffusion-webui-master\modules\processing.py", line 1156, in sample
        return self.sample_hr_pass(samples, decoded_samples, seeds, subseeds, subseed_strength, prompts)
      File "L:\AI\stable-diffusion-webui-master\modules\processing.py", line 1242, in sample_hr_pass
        samples = self.sampler.sample_img2img(self, samples, noise, self.hr_c, self.hr_uc, steps=self.hr_second_pass_steps or self.steps, image_conditioning=image_conditioning)
      File "L:\AI\stable-diffusion-webui-master\modules\sd_samplers_kdiffusion.py", line 188, in sample_img2img
        samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "L:\AI\stable-diffusion-webui-master\modules\sd_samplers_common.py", line 261, in launch_sampling
        return func()
      File "L:\AI\stable-diffusion-webui-master\modules\sd_samplers_kdiffusion.py", line 188, in <lambda>
        samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "L:\AI\stable-diffusion-webui-master\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "L:\AI\stable-diffusion-webui-master\repositories\k-diffusion\k_diffusion\sampling.py", line 594, in sample_dpmpp_2m
        denoised = model(x, sigmas[i] * s_in, **extra_args)
      File "L:\AI\stable-diffusion-webui-master\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "L:\AI\stable-diffusion-webui-master\modules\sd_samplers_cfg_denoiser.py", line 125, in forward
        x_in = torch.cat([torch.stack([x[i] for _ in range(n)]) for i, n in enumerate(repeats)] + [x])
      File "L:\AI\stable-diffusion-webui-master\modules\sd_samplers_cfg_denoiser.py", line 125, in <listcomp>
        x_in = torch.cat([torch.stack([x[i] for _ in range(n)]) for i, n in enumerate(repeats)] + [x])
      File "L:\AI\stable-diffusion-webui-master\modules\sd_samplers_cfg_denoiser.py", line 125, in <listcomp>
        x_in = torch.cat([torch.stack([x[i] for _ in range(n)]) for i, n in enumerate(repeats)] + [x])
    IndexError: index 1 is out of bounds for dimension 0 with size 1
```

### Unprompted version

 v10.1.5

### WebUI version

1.6.0

### Other comments

I've seen there's another recent issue with batch count > 1 but it looks like a different issue.

**Comment by ThereforeGames** [comment]
Hi @entusiastaIA,

Thank you for reaching out. Please try updating to v10.2.1 and let me know if the issue persists - I am able to correctly generate images with the following conditions in the latest version:

- `batch_count` > 1
- Hires. fix enabled
- Using the Wizard to auto-include a complex template (our Beautiful Soul addon) in txt2img mode

If it's still giving you trouble, I may need to see the contents of your template to diagnose further. Thanks.

**Comment by entusiastaIA** [comment]
Hello there! Thank you very much for the quick update. Seems like it has improved a lot, but there's still an issue. Now the images are generated and processed, but when enabling hi res fix seems like if the prompt for the first image got stuck and applied to all the images (despite the text files generated state that they have the correct prompt). Look, these are the images without enabling hires fix and batch count 3 (I edited one to remove NSFW stuff):

![927807304-512x512-20231029_130151_740418](https://github.com/ThereforeGames/unprompted/assets/113212323/8fc56024-f335-4b50-b237-8e5d6060f891)

![927807305-512x512-20231029_130311_475934](https://github.com/ThereforeGames/unprompted/assets/113212323/61aa840c-9db8-49db-8fb5-8e7570967b3c)

![927807306-512x512-20231029_130313_189880](https://github.com/ThereforeGames/unprompted/assets/113212323/13627337-f16f-4a85-91ad-65430c7d8575)

And these are the same seeds after enabling high res fix:

![927807304-1024x1024-20231029_130226_584184](https://github.com/ThereforeGames/unprompted/assets/113212323/838ff9f0-d1f8-470e-ae69-9c807c71c303)

![927807305-1024x1024-20231029_130032_287798](https://github.com/ThereforeGames/unprompted/assets/113212323/e8b6fc2e-3077-4752-a613-aadd51b852c0)

![927807306-1024x1024-20231029_130254_514155](https://github.com/ThereforeGames/unprompted/assets/113212323/317f6ce6-2610-4f09-be9d-410cd115576e)

You can pretty much tell that is the prompt for the first one the one that is being used again and again, despite the text files with the prompts inside stating otherwise. For example the last uses "amidst a river with clear waters."; obviously the 512 image is obeying that, while the 1024 is obeying the place from the first image: "amidst an airport terminal."

Again, thank you very much.

P.S: I posted this very same answer into a wrong and closed issue first, sorry about that.

**Comment by ThereforeGames** [comment]
Ah, it looks like there were a couple more variables related to Hires Fix that I neglected to sync with batch processing.

Could you try the new v10.2.2 and let me know if it produces the expected results? It seems to be receiving the right prompts on my device now.

Thanks!

**Comment by entusiastaIA** [comment]
Yes! I also made some tests to ensure that not only positive but negative prompts where able to be mixed again too and everything seems to be working now!!

Thank you very much!

P.S: I have been trying to find a way to DM you, but nor in your GitHub, Twitter or YT I find any contact info. I want to send some support but nor GitHub nor Patreon are good for me. Feel free to reach me out: ainecaptain@gmail.com

**Comment by ThereforeGames** [comment]
Great, glad to hear it's working! 👍

I'll close the issue and send you an email from developer@therefore.games.
