### ISSUE TITLE
show the controlnet image after generation

### ISSUE THREAD

**Issue by redstoneguy10ls** [ThereforeGames/unprompted#216]
### Due diligence

- [X] I checked for similar issues and couldn't find any.
- [X] My WebUI and Unprompted are both up-to-date.
- [X] I disabled my other extensions but the problem persists.

### Describe the bug

IDK if its a bug per say but I'm wondering if there's a way to get the image that you use for controlnet to display with the generated image like what happens when you don't use unpromted

### Unprompted version

10.3.1

### WebUI version

current

**Comment by ThereforeGames** [comment]
Hi @redstoneguy10ls,

Thanks for reaching out. I have a couple questions:

- Does this issue occur even when you're not using any shortcodes in the prompt? (If it's shortcode-specific, please provide an example prompt.)
- What steps are taken to add the ControlNet image to your output window, i.e. do I need to enable a setting somewhere?

I will attempt to reproduce it soon.

**Comment by redstoneguy10ls** [comment]
uh so basically when i use an image directly in controlnet, like just drag the image into controlnet it'll appear beside the output, but if i use [set cn_0_image][choose][filelist "D:/ai/poses/192SexyFemaleBikini_v10/sexy women poses contolnetposes.com/poses*.png"][/choose][/set] then it won't. the image is what happens without unprompted
<img width="101" alt="image" src="https://github.com/ThereforeGames/unprompted/assets/29243088/862d6cc0-e248-4d06-9c72-fe638e2c1c0b">

**Comment by redstoneguy10ls** [comment]
update, i get this error message, which idk what it means  Could not set ControlNet value (cn_0_image): ImageIO does not generally support reading folders. Limited support may be available via specific plugins. Specify the plugin explicitly using the `plugin` kwarg, e.g. `plugin='DICOM'`
