### ISSUE TITLE
processor_res vars won't work with sdxl controlnets

### ISSUE THREAD

**Issue by magicbot42** [ThereforeGames/unprompted#221]
### Due diligence

- [X] I checked for similar issues and couldn't find any.
- [X] My WebUI and Unprompted are both up-to-date.
- [X] I disabled my other extensions but the problem persists.

### Describe the bug

controlnet values like cn_0_processor_res=1024 no longer seem to be setting the appropriate variable in the p object for sdxl controlnet use cases.  I'm not sure if the name changed or something, but I'm on the latest dev branch of automatic1111 with latest unprompted only and it's not setting the value.  No matter what number put in these _processor_res vars, I get out 512 resolution which is pretty small considering it's working on 1024 images for sdxl.  All of the rest of the overrides from the manual that we can set via [sets] do still appear to be working.  It's just the processor_res vars that won't connect any more. 

### Prompt

NA

### Log output

```shell
NA
```

### Unprompted version

 v10.5.0

### WebUI version

v1.6.0-372-g8aa51f68 

### Other comments

Thanks again for this amazing extension

**Comment by ThereforeGames** [comment]
Hi @magicbot42,

Thank you for reaching out! I'm glad you're still enjoying Unprompted.

I haven't been able to reproduce this issue - in my tests, setting `cn_x_processor_res` behaves as expected. We can print the properties of the CN object to confirm that `processor_res` is still the correct variable name:

```
UiControlNetUnit(enabled=False, module='openpose_full', model='None', weight=1, image=None, resize_mode='Crop and Resize', low_vram=False, processor_res=768, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', save_detected_map=True)
```
```
UiControlNetUnit(enabled=False, module='ip-adapter_clip_sdxl', model='ip-adapter_xl [4209e9f7]', weight=1, image=None, resize_mode='Crop and Resize', low_vram=False, processor_res=512, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', save_detected_map=True)
```

I'm on the A1111 dev branch as well. So that leaves me with a couple diagnostic questions:

- Is your ControlNet extension up-to-date?
- Which CN model exhibits this problem? Have you tried with other models?

Thanks!

**Comment by magicbot42** [comment]
What seems to be happening is that it only set teh processor_res on the first controlnet in a multicontrolnet setup.  The subsequent control nets don't get their res updated.

**Comment by magicbot42** [comment]
Apologies, I had pixelperfect set to 1 for some of the controlnet units, and since that cancels the preprocessor_res variable it was defaulting to 512.  This is a non-issue.  Sorry about that..

**Comment by ThereforeGames** [comment]
> Apologies, I had pixelperfect set to 1 for some of the controlnet units, and since that cancels the preprocessor_res variable it was defaulting to 512. This is a non-issue. Sorry about that..

No worries, it's good to know what was causing it!
