### ISSUE TITLE
Secondary shortcode not working with filter_tags

### ISSUE THREAD

**Issue by Tommy2103** [ThereforeGames/unprompted#233]
### Due diligence

- [X] I checked for similar issues and couldn't find any.
- [X] My WebUI and Unprompted are both up-to-date.
- [X] I disabled my other extensions but the problem persists.

### Describe the bug

I'm trying to use the filter shortcode and I'd like to use a variable to set the tag i want to filter.
In order to do this I tried to retrieve the variable inside `[filter_tags]`, but it doesn't work because it recognize as a tag the string `"{get filter}"` (both with or without double quotes).
Am i missing something? Is there an alternative?

### Prompt

```
[set filter]spam[/set]
[filter_tags "{get filter}" _debug]
[tags "spam"]spam[/tags]
[tags "eggs"]eggs[/tags]
```

### Log output

```shell
2024-02-10 21:51:52,944  (INFO)     [Unprompted.filter_tags] Parg tags: ['{get', 'filter}', '_debug']
2024-02-10 21:51:52,944  (INFO)     [Unprompted.filter_tags] Kwarg tags: {}
2024-02-10 21:51:52,945  (INFO)     [Unprompted.tags] Failed tags block: ['spam'] {}
2024-02-10 21:51:52,945  (INFO)     [Unprompted.tags] Failed tags block: ['eggs'] {}
2024-02-10 21:51:52,946  (INFO)     [Unprompted]
```

### Unprompted version

v10.6.0

### WebUI version

1.7.0

**Comment by ThereforeGames** [comment]
Hi @Tommy2103,

I have implemented secondary tag support for `[filter_tags]` arguments in Unprompted v11.0.1:

![image](https://github.com/ThereforeGames/unprompted/assets/95403634/5e94e892-e404-4502-9e80-33eae439a48f)

Let me know if you have any questions. Thank you.
