### ISSUE TITLE
Guide to how to use Bodysnatcher

### ISSUE THREAD

**Issue by youlijie** [ThereforeGames/unprompted#235]
### Due diligence

- [X] I checked for similar issues and couldn't find any.
- [X] My WebUI and Unprompted are both up-to-date.
- [X] I disabled my other extensions but the problem persists.

### Describe the bug

Will it be possible to have a guide how to use the Bodysnatcher template because I don't know what I'm doing wrong, but it's not working

### Unprompted version

v10.6.0

### WebUI version

1.8.0

**Comment by ThereforeGames** [comment]
Hi @youlijie,

I just updated the documentation for Bodysnatcher with a new "Usage Guide" section - check it out and let me know if the problem persists.

Bodysnatcher also received quite a few updates in v11.0.0, so whatever wasn't working before might have been resolved!
