### ISSUE TITLE
Disable pnginfo

### ISSUE THREAD

**Issue by CaptainVarghoss** [ThereforeGames/unprompted#244]
### Due diligence

- [X] I checked for similar requests and couldn't find any.
- [X] I read the manual and am at least reasonably sure this idea/feature doesn't already exist.

### Your idea

It would be nice to be able to disable the addition of Unprompted information to the pnginfo.

I do understand why one might want it, but in my case at least it's not useful for anything and simply adds more data.

**Comment by ThereforeGames** [comment]
Hi @CaptainVarghoss,

If you haven't already, try disabling `ui.show_extra_generation_params` in your config file. I believe the generation parameters also get added to the resulting PNG metadata.

You can also disable the functionality entirely in the WebUI settings: https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/5806

**Comment by CaptainVarghoss** [comment]
That does the trick, thanks.
