### ISSUE TITLE
Seeds are deterministic?

### ISSUE THREAD

**Issue by CaptainVarghoss** [ThereforeGames/unprompted#246]
### Due diligence

- [X] I checked for similar issues and couldn't find any.
- [ ] My WebUI and Unprompted are both up-to-date.
- [X] I disabled my other extensions but the problem persists.

### Describe the bug

Unsure if this is actually intended or not as it may just be "the way it works" but I figured I would put it out there anyway since I noticed it was happening.

When generating images with unprompted enabled (even without any shortcodes) the seeds repeat in the same order from a given seed.

For example:
1.) Generate image with seed 100
2.) Generate 10 images with 'random' seeds
3.) Generate image with seed 100 and a slightly modified prompt (in my case I added a word to the negative prompt)
4.) Generate 10 images with 'random' seeds

After doing this I noticed the 10 'random' images from both sets had the exact same list of seeds.
None of this was done using batches or scripts, or anything thing else I could determine as being any kind of sequential.

In this example image, the first of 5 images was generated with a specific seed, then seed was set to -1 in the UI and 4 images generated, then the seed was reset to match the first one, then again set to -1 and generated 4 more images. You can see that it 'randomly' generated the same 4 seeds the second time through. This particular test was done with no shortcode in the prompts.
![NVIDIA_Share_ygBE0m1eek](https://github.com/ThereforeGames/unprompted/assets/130285881/a0b9fb02-c552-47fa-8599-5e32cbf22717)

### Unprompted version

10.8.0 

### WebUI version

1.8.0

**Comment by ThereforeGames** [comment]
Hi @CaptainVarghoss,

Thank you for reaching out.

I believe I was able to resolve this issue in the newly released v10.10.0 - feel free to give it a try and let me know if it gives you any further trouble. Thanks!

**Comment by CaptainVarghoss** [comment]
Looks like the new version fixed it. Thanks!
