### ISSUE TITLE
ModuleNotFoundError: No module named 'lib.shared'

### ISSUE THREAD

**Issue by Harvester62** [ThereforeGames/unprompted#25]
After updating the SD Web UI to Commit hash: 8fba733c0906dd3a80c0a3873793cffa4c78ce04 this error message is being displayed in the console, right after the "Launching Web UI with arguments":

Error loading script: unprompted.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\stable-diffusion-webui\extensions\unprompted\scripts\unprompted.py", line 18, in <module>
    from lib.shared import Unprompted
ModuleNotFoundError: No module named 'lib.shared'

Unprompted then doesn't appear available in the Web UI.

**Comment by B3N50N** [comment]
i've found the problem,
i don't think this is cause by this extension
probably there are duplicate "lib" in sys.path stack
i'll keep finding a way to workout

**Comment by ThereforeGames** [comment]
Hi,

I have not been able to reproduce this error even after updating A1111 to the latest version. It sounds like @B3N50N has identified the issue correctly - if there are any workarounds I can make to the extension, such as renaming the "lib" folder if it conflicts with a common sys.path setup, I would be happy to do so.

**Comment by B3N50N** [comment]
@ThereforeGames yes, i've rename the "lib" to "Un_lib" and changed all the nessecery part of code,  and now i can use this extension with no issue

**Comment by Harvester62** [comment]
I've just updated/syncronized all repositories including Unprompted but at startup I still get this error:

Error loading script: unprompted.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\stable-diffusion-webui\extensions\unprompted\scripts\unprompted.py", line 18, in <module>
    from lib.shared import Unprompted
ModuleNotFoundError: No module named 'lib.shared'

Have @B3N50N fix been already applied?

**Comment by ThereforeGames** [comment]
Hi @Harvester62,

After more thought, I am hesitant to change the "lib" directory name without knowing exactly what causes the crash for you and @B3N50N - I don't want to inadvertently break the extension for others in the process. Let's try some other solutions first, if that's okay.

Attached is a modified version of unprompted.py that will hopefully allow my import statements to take higher precedence in the sys.path stack.

[unprompted_v2,0,2_modified.zip](https://github.com/ThereforeGames/unprompted/files/10185659/unprompted_v2.0.2_modified.zip)

Could you give this file a try and let me know if the crash persists? The file in the archive should extract to `automatic-stable-diffusion-webui\extensions\unprompted\scripts`, replacing what's already there. You will need to restart the WebUI after swapping out the file.

Thanks!

**Comment by B3N50N** [comment]
@ThereforeGames i have try use sys.path.insert , but still don't work

**Comment by Harvester62** [comment]
Hi, thank you for the file but unfortunately the problem persists, same error message.

**Comment by ThereforeGames** [comment]
Hi @B3N50N and @Harvester62,

Thank you for trying the modified script, sorry to hear it did not resolve the issue.

While working on Unprompted v4.0.0 (which is out now btw!) I ran into a similar problem. It was caused by having a `lib` folder in the root of the A1111 WebUI.

Do either of you have a `lib` folder there, and if so, what's inside of it?

**Comment by B3N50N** [comment]
no i don't have it

**Comment by gsgoldma** [comment]
I have this issue too.

**Comment by tacusin** [comment]
Also had this issue, resolved it by making the lib folder to libb and changing the script. In sure me telling you this doesn't help but some like to know how many are affected by an issue so figured I'd post

**Comment by gsgoldma** [comment]
> Also had this issue, resolved it by making the lib folder to libb and changing the script. In sure me telling you this doesn't help but some like to know how many are affected by an issue so figured I'd post

that worked. i had to do it about 3 or 4 times replacing lib to libb for every new file that traceback claimed was trying from 'lib.whatever'. think there was one or two in shared

**Comment by ThereforeGames** [comment]
Hey guys,

I appreciate the continued feedback on this issue.

It sounds like I may need to change the "lib" folder name, at least temporarily.

Admittedly, I'm not thrilled about this course of action because I don't really understand what's causing the error in the first place. If there's a sys path conflict, there is probably some simple fix for the import statements, but my research has turned up short thus far.

If you don't mind, I would like to collect a bit more diagnostic info from anyone having this issue:

- Are you able to run `unprompted_dry.py` if you put the app in another location (outside the A1111 WebUI folder?)
- What OS and version of Python are you on?
- Could you try adding an empty file called `__init__.py` inside of the `lib` directory? To my knowledge, this isn't necessary in newer versions of Python, but [it appears there are some cases](https://stackoverflow.com/a/65046316) where it's still important to include this file.

Thank you! I will change the folder name if we still can't get to the bottom of it.

**Comment by Harvester62** [comment]
Thank you @ThereforeGames for taking care of this issue. I would be more than willing to help you find out the source of the problem and I will provide you all the information I can. Unfortunately, Unprompted doesn't even start up after the above error therefore I am unable to do a Dry Run of it. What I am sure about is that for some time it worked in the past, as you might remember about the issue with Dynamic Prompts.
Anyway, I here follows the info I can provide you at the moment:
OS: Windows 10 Pro 64 bit 22H2 build 19045.2364
Python version 3.10.6
Added an empty `__init__.py` file inside the `lib` directory but it didn't make any difference, same error. Let us know if there is anything else we can do for you.

And, by the way, I wish you all a Very Merry Xmas!

**Comment by spinagon** [comment]
I launched python in verbose mode, and might have found the culprit.
```
# trying F:\ssb\stable-diffusion-webui\repositories\BoostingMonocularDepth\lib\shared.cp310-win_amd64.pyd
# trying F:\ssb\stable-diffusion-webui\repositories\BoostingMonocularDepth\lib\shared.pyd
# trying F:\ssb\stable-diffusion-webui\repositories\BoostingMonocularDepth\lib\shared.py
# trying F:\ssb\stable-diffusion-webui\repositories\BoostingMonocularDepth\lib\shared.pyw
# trying F:\ssb\stable-diffusion-webui\repositories\BoostingMonocularDepth\lib\shared.pyc
Error loading script: unprompted.py
Traceback (most recent call last):
  File "F:\ssb\stable-diffusion-webui\modules\scripts.py", line 195, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "F:\ssb\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "F:\ssb\stable-diffusion-webui\extensions\unprompted\scripts\unprompted.py", line 21, in <module>
    from lib.shared import Unprompted
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lib.shared'
```
repositories\BoostingMonocularDepth has lib folder too

It's not in sys.path by the moment of import, but it's cached in sys.modules

**Comment by Harvester62** [comment]
Hi, @ThereforeGames , Happy New Year! Do you have any news about this issue? Any possible solution? Thank you.

**Comment by gsgoldma** [comment]
tried to reinstall to fix this and..i got anerror when downloading a file that chat gpt interpreted:

It looks like you are trying to download a file from a Git repository and are encountering an error that says the repository is over its data quota. This means that the repository owner has exceeded the amount of data that they are allowed to store in the repository, and as a result, access to the repository has been restricted.

To fix this error, the repository owner will need to purchase more data packs to increase the repository's data quota. They can do this by logging in to their account on the hosting service (e.g. GitHub, GitLab) and going to the repository's settings or billing page. Alternatively, they can try moving some of the larger files in the repository to a different storage service and linking to those files using Git Large File Storage (LFS).

**Comment by Harvester62** [comment]
@ThereforeGames While trying to find a solution to the recent updates to Gradio and UI layout, which messed up a little my local installation for some reason, I ended up removing the venv and rebuilding it, which solved the problems. Then, while adding and testing back the many extensions I need to properly work on the Italian localization, for a moment, Unprompted was loaded successfully but I kept activating extensions and at the end Unprompted got back not to work again. 
I suspect that there might be some conflicts with other extensions, but now that they all works I need to work to the translations before I even thing of doing further tests, perhaps in the weekend. For the moment I deactivated Unprompted but I definitely wish to be able to activate it so to check for any new translations needed (did you add anything else to the UI?).

**Comment by Harvester62** [comment]
Just an update for you, @ThereforeGames , after today's update of SWUI (Commit hash: 194cbd065e4644e986889b78a5a949e075b610e8) I decided to give Unprompted another try and removed it from the Deactivated list of Extensions in the config.json file but I got errors and the backend didn't started, so I deleted the config.json file and at the same time added gradio==3.16.2 to the Dreambooth requirements.txt (was reported as to solve Dreambooth not starting correctly, but this is another story). The latter resolved the problem so that the backend finally started, but Unprompted displayed an error message, this time different from the above reported one, see below, hope it helps:

Error loading script: unprompted.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\scripts.py", line 218, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\stable-diffusion-webui\extensions\unprompted\scripts\unprompted.py", line 12, in <module>
    import lib.shortcodes as shortcodes
ModuleNotFoundError: No module named 'lib.shortcodes'

**Comment by gsgoldma** [comment]
I found the conflict extension. It's depth map script, based on the detective work of spinagon, I looked up what used monocular depth. it was depth-map script, big surprise. 

i removed depth map script, unprompted loaded up without error

so that's the conflict extension, I'm not sure how to resolve it other than only have them in the folder at mutually exclusive times, until one them changes their lib folder or something else.

**Comment by ThereforeGames** [comment]
Hi folks,

My apologies for not responding here in a while.

After reading your feedback, I hypothesize that this issue may be caused by a flaw in A1111's extensions framework.

I examined the code of the depth map script and it doesn't appear to be doing anything wrong or unusual as far as importing files from "lib." Actually, they're doing it pretty much the same way I am.

I plan now to install the extension for further debugging. If I can't solve the issue in my code, I will rename the folder to something like `lib_unprompted` in the next update.

Thanks for bearing with me on this.

**Comment by ThereforeGames** [comment]
Hello again,

I have released Unprompted v5.2.0 in which the `lib` folder has been renamed to `lib_unprompted`. Please give it a try and let me know if it resolves the loading issue. (Make sure to completely restart your A1111 WebUI after fetching the update!)

**Comment by gsgoldma** [comment]
can confirm there no more errors in console with depth map installed

**Comment by ThereforeGames** [comment]
Awesome! Glad to hear it.

I'll mark this issue as closed and maybe open a new one at the A1111 repo for further investigation.

**Comment by Harvester62** [comment]
I confirm that even for me, now, Unprompted v5.2.0 works! I'll localize the UI to Italian language soon.
