### ISSUE TITLE
{choose} stopped working in [array _append="..."]

### ISSUE THREAD

**Issue by Specthram** [ThereforeGames/unprompted#256]
### Due diligence

- [X] I checked for similar issues and couldn't find any.
- [X] My WebUI and Unprompted are both up-to-date.
- [X] I disabled my other extensions but the problem persists.

### Describe the bug

hello, {choose} does not work in array, I have the issue since I updated yesterday. It looks like `|` is misinterpreted inside [array myArray _append="{choose 1}tata|toto{/choose}"].

### Prompt

[array myArray]
[array myArray _append="{choose 1}tata|toto{/choose}"]

### Log output

```shell
can't run it atm, but something like "unexpected /choose blabla" array.py.lxxx
```

### Unprompted version

129424860d3ee299151fccb27cfb82b4991f51cb

### WebUI version

v1.10.0-RC

**Comment by ThereforeGames** [comment]
Hi @Specthram,

Thank you for reaching out.

The order of operations for `_append` was changed such that it splits by delimiter (`|`) before parsing the value(s). This resolved a number of other weird interactions with `[array]` but had the unfortunate side effect of breaking `[choose]`.

Two solutions come to mind:

1. Pass a different `_delimiter` to `[array]`. For example: `[array myArray _delimiter="nothing" _append="{choose}tata|toto{/choose}"]` should allow your code to execute successfully.

2. Set up your `[choose]` in a separate `[function]` and `[call]` it inside your `[array]`. For example:

```
[function my_func]
[choose]toto|tata[/choose]
[/function]
[array my_array _append="{call my_func}"]
```

Let me know if you have any questions. Thank you.
