### ISSUE TITLE
Truncation of Strings

### ISSUE THREAD

**Issue by alexanderdutton** [ThereforeGames/unprompted#26]
Thanks for the extension. I've been using Dynamic Prompts, but recently am exploring Unprompted for a bit more versatility of options.

So I've been converting some of my wildcard files over, learning the format as I go, and so far I've noticed some unusual truncation.

For the code

>a woman wearing  outfit [repeat  _times="<random 2>"] and another thing[/repeat]

I receive:

> a woman wearing outfi

When it triggers the repeat, there is no truncation.

>a woman wearing outfit and another thing

I've also had this happening with [file] choices, even where they are in the middle of a prompt, and so it must be happening before that.

Adding a double-space seems to truncate simply the space, so is a current solve for me, if perhaps not the ideal operation.

Thanks for any assistance, and I appreciate the work.

**Comment by ThereforeGames** [comment]
Hi @alexanderdutton,

Thank you for reaching out! It looks like there was an issue with the string sanitization feature - this has been resolved in v2.0.1.

Also, please note that secondary tag syntax has changed in v2.0.0. Your example code would be updated as such:

> a woman wearing outfit [repeat "{random 2}"] and another thing[/repeat]

Please let me know if you have any questions. I'm glad you're liking the extension!
