### ISSUE TITLE
[switch] function not working

### ISSUE THREAD

**Issue by ZealousMagician** [ThereforeGames/unprompted#32]
I tested [switch] as follows:
[set testy]2[/set]

[switch testy]
  {case 1}one{/case}
  {case 2}two{/case}
  {case}three{/case}
[/switch]
And it gave no output. The debug notes that it loads the file, sets "testy" to 2, and then says "result 0:".

**Comment by ThereforeGames** [comment]
Fixed in v4.2.1, thank you for bringing it to my attention @ZealousMagician !
