### ISSUE TITLE
get shortcode doesn't understand eval shortcode

### ISSUE THREAD

**Issue by valconius** [ThereforeGames/unprompted#34]
Working, result is 0.
```
[sets n=0]
[get n]
```

Also working, result is 0.
```
[sets n=0]
[get "n"]
```

Fails:
```
[sets n=0]
[get "'n'"]
```

Fails:
```
[sets n=0]
[get "{eval}'n'{/eval}"]
```

I encountered this problem while trying to build a symbol name and then retrieve that symbol:
```
[sets max0=5]
[sets max1=10]
[sets n="{random _min 0 _max 1}"]
[get "'max' + str(n)"] <-- does nothing
```

Simpler example that fails:
```
«sets o0="one¦two"»
«sets o1="cat¦dog"»
«get "{choose}'o0'¦'o1'{/choose}"»
```

**Comment by ThereforeGames** [comment]
Hi @valconius,

I'm catching up on older issues I missed - this one caught my eye.

It is possible to evaluate an arbitrary expression with `[get]` using the `_var` kwarg:

```
[sets max0=5 sets max1=10]
[sets n="{random _min=0 _max=1}"]
[get _var="max{get n}"]
```

This example would return either 5 or 10.
