### ISSUE TITLE
txt2mask non-zero padding causes mask to translate

### ISSUE THREAD

**Issue by credman0** [ThereforeGames/unprompted#37]
Adding a padding to the txt2mask parameters seems to cause the mask to translate/shift from its starting point. Prompt used was:

[txt2mask smoothing=10 padding=<n>]eyes[/txt2mask] closed eyes, masterpiece, best quality

With 0 denoising strength and a latent nothing fill to show the mask.

Original:
![01064-421082352](https://user-images.githubusercontent.com/20376935/209504501-7b63a7ea-aefa-4954-b85a-c93fd8d804fc.png)

0 padding:
![01070-421082349-padding0](https://user-images.githubusercontent.com/20376935/209504554-cd1d0241-ceb6-4e7d-85b2-a10cae67457f.png)

30 padding:
![01069-421082349-padding30](https://user-images.githubusercontent.com/20376935/209504532-3378cf08-103e-4bb3-bf64-93b0f17aa41d.png)

50 padding:
![01071-421082349-padding50](https://user-images.githubusercontent.com/20376935/209504570-eed22095-c285-4587-99f0-628daae30e4d.png)

**Comment by ThereforeGames** [comment]
Fixed in v5.0.0. Thank you!
