### ISSUE TITLE
How to use the negative_mask argument for [text2mask]? 

### ISSUE THREAD

**Issue by syddharth** [ThereforeGames/unprompted#43]
I am using this:
[txt2mask padding=80 smoothing=20 show ]person[/txt2mask], [txt2mask negative_mask show] head [/txt2mask], spiderman
want to subtract face mask from the person mask. The negative_mask doesn't seem to subtract from the content mask.

![image](https://user-images.githubusercontent.com/15185829/210208181-b31b4649-f3a2-4cd1-9ed4-235229868627.png)
![image](https://user-images.githubusercontent.com/15185829/210208302-c53736df-3a3a-4635-8d63-8615933b1cdd.png)

**Comment by ThereforeGames** [comment]
Hi @syddharth,

Thank you for reaching out!

You do not need to use two instances of `[txt2mask]` to subtract "head" from "person." Instead, supply your negative mask as a keyword argument as shown below:

```
[txt2mask padding=80 smoothing=20 negative_mask="head" show]person[/txt2mask]spiderman
```

![image](https://user-images.githubusercontent.com/95403634/210209394-238cc6ae-1eda-47af-80cf-6747d20acb2e.png)

Let me know if you have any questions.

**Comment by syddharth** [comment]
Awesome! Thanks for the quick response, this helps! 👍

**Comment by syddharth** [comment]
@ThereforeGames is it possible to have padding around the negative_mask?

**Comment by nistvan86** [comment]
> @ThereforeGames is it possible to have padding around the negative_mask?

I have a similar question, but with negative padding. I want to select only the central face of a person so I can put his head into a helmet. "(lower face:0.3)" seems to do the trick, but still un-selects a bit too much, often including partially the ears.
