### ISSUE TITLE
I get an error and it doesn't work.

### ISSUE THREAD

**Issue by mokumoku4865** [ThereforeGames/unprompted#49]
After updating and running Webui, I get the following error and prompts from the file do not load properly.

Prompt generated in 0.0 seconds
Error running process: F:\tools\stable-diffusion\extensions\unprompted\scripts\unprompted.py
Traceback (most recent call last):
  File "F:\tools\stable-diffusion\modules\scripts.py", line 347, in process
    script.process(p, *script_args)
  File "F:\tools\stable-diffusion\extensions\unprompted\scripts\unprompted.py", line 218, in process
    setattr(p,att,Unprompted.shortcode_user_vars[att])
AttributeError: can't set attribute 'sd_model'

**Comment by Nefrasky** [comment]
same issue here

**Comment by wizardt** [comment]
same issue here

**Comment by mangocan** [comment]
I've got the same issue

**Comment by valconius** [comment]
same issue, even with more recent commits, it also seems to reset my model to sd15 sometimes, not that i can complain very much as i accidentally made some nice generated images with sd15 without realizing it! as an aside, the "x-y infinity grid" extension had the same problem and fixed it recently, perhaps by looking at their code you can copy-paste a solution.

**Comment by yiouyou** [comment]
Same here, something is broken

**Comment by conncomg123** [comment]
You can simply comment out lines 216-218 of unprompted.py.

**Comment by ThereforeGames** [comment]
Hi folks,

I implemented a workaround for this issue in v5.1.0. Automatic has been updating the WebUI's architecture quite a lot recently, so please bear with me as I learn how to take advantage of some of the new features.

Interestingly, it seems that we extension developers now have access to a `sd_model` object which means Unprompted may allow you to switch your active checkpoint on the fly soon. Stay tuned for that.
