### ISSUE TITLE
Cannot load Config

### ISSUE THREAD

**Issue by unwize** [ThereforeGames/unprompted#5]
Error on launch:

```
(SETUP) Initializing Unprompted object...
(SETUP) Loading configuration files...
Error loading script: unprompted.py
Traceback (most recent call last):
  File "D:\Projects\Tools\stable-diffusion-webui\modules\scripts.py", line 155, in load_scripts
    exec(compiled, module.__dict__)
  File "D:\Projects\Tools\stable-diffusion-webui\scripts\unprompted.py", line 15, in <module>
    Unprompted = Unprompted()
  File "D:\Projects\Tools\stable-diffusion-webui\unprompted\lib\shared.py", line 22, in __init__
FileNotFoundError: [Errno 2] No such file or directory: './unprompted/config.json'
```

I placed the `scripts` files in the root and the `unprompted` files in the extensions folder. Is this not correct? Seems like a simple path issue.

**Comment by ThereforeGames** [comment]
> I placed the scripts files in the root and the unprompted files in the extensions folder. Is this not correct? Seems like a simple path issue.

Hi, the Unprompted folder needs to go in the root of the A1111 WebUI - not in `extensions`.

That said, I'm upgrading Unprompted to an extension as we speak, so the installation procedure will change soon. **EDIT:** It's out! Check the frontpage for new install instructions.
