### ISSUE TITLE
(ERROR) [shortcodes\basic\file.py] No files found at this location: ...stable-diffusion-webui\extensions\unprompted/./templates/human/main.txt

### ISSUE THREAD

**Issue by edgartaor** [ThereforeGames/unprompted#62]
I got this error

`(ERROR) [shortcodes\basic\file.py] No files found at this location: H:\projects\StableDiffusion\AUTOMATIC1111\stable-diffusion-webui\extensions\unprompted/./templates/human/main.txt`

I think is trying to merge a Windows path with Linux path.

**Comment by OEvgeny** [comment]
I got it too. Replace "./templates" in unprompted config with "templates". The config is located in extension folder

**Comment by ThereforeGames** [comment]
Hi @edgartaor and @OEvgeny ,

Thank you for reaching out!

I have changed the default `template_directory` value from `./templates` to `template` in Unprompted v7.4.0. The new value seems to work fine on Windows as well.

Let me know if you run into any similar issues. Thanks!

**Comment by edgartaor** [comment]
That didn't work for me. 
I edit the file shortcodes\basic\file.py:19
```
# else: path = self.Unprompted.base_dir + "/" + self.Unprompted.Config.template_directory + "/" + file_string + self.Unprompted.Config.txt_format
else: path = os.path.join(self.Unprompted.base_dir,self.Unprompted.Config.template_directory, file_string) + self.Unprompted.Config.txt_format
```

And write the prompt like this
`[file common\examples\human\main]`
or like this:
`[file common/examples/human/main]`

That way loaded the files correctly.

I hope this help
