### ISSUE TITLE
couple comments on img2pez

### ISSUE THREAD

**Issue by bakkot** [ThereforeGames/unprompted#69]
I spend a while playing with [the repo](https://github.com/YuxinWenRick/hard-prompts-made-easy). I have a few observations you might be interested in:

- 3000 iterations is _way_ more than necessary. I generally stop seeing much improvement after about 200. Beyond that the improvements are all marginal, and if you want more iterations you might as well just re-run it.
- With a [small tweak](https://github.com/YuxinWenRick/hard-prompts-made-easy/pull/5/files#diff-fe860cddb002afbf16cba34b7f1dc4a6fad01c30703d8eb9a512b095c7146095), you can get it to give you the best candidates as it finds them. That way if you stop it early you don't have to throw all your progress away.
- You can pass it multiple images and it will optimize a prompt across all of them, which is good for style transfer.
- If you use the "ViT-H-14"/"laion2b_s32b_b79k" config, the prompts actually work in Midjourney too. Not something you can directly incorporate but maybe worth documenting.
- 16 tokens prompt length works better than 8, according to the paper (and in my experience).

**Comment by ThereforeGames** [comment]
Hi @bakkot ,

Thank you for reaching out!

Those are great suggestions. I will release an update later today with optimized defaults for img2pez.

Could you point me in the direction of the "ViT-H-14"/"laion2b_s32b_b79k" config? I'd like to understand why this isn't something we can directly incorporate.

Thanks again!

**Comment by bakkot** [comment]
> I'd like to understand why this isn't something we can directly incorporate.

Oh, I just meant that the UI isn't hooked up to Midjourney. So you can get a prompt which will work in Midjourney (as well as in SD 2.1), but the user will have to copy-paste it over to Midjourney themselves.

The config I'm referring to is the `clip_model` and `clip_pretrain` [parameters](https://github.com/YuxinWenRick/hard-prompts-made-easy#parameters). `ViT-H-14` and `laion2b_s32b_b79k` are the appropriate values for those parameters to generate prompts for Midjourney and SD 2.1 (and derivatives thereof). `ViT-L-14` and `openai`  are appropriate values to generate prompts for SD 1.4/1.5 (and derivatives thereof).

**Comment by ThereforeGames** [comment]
I see, thank you! I'll make a note of it in the Manual.

Your other suggestions have been implemented in Unprompted v7.4.0. :)
