### ISSUE TITLE
text2mask is generating a mask even when not enabled

### ISSUE THREAD

**Issue by gsgoldma** [ThereforeGames/unprompted#70]
I have to uncheck from the top of the script, because having show mask/auto prompt unchecked doesn't stop it from working. if i having nothing in the text field and click generate output it shows 'gu' in the middle where a word would go
that results in a vague outline around my one character because it's close to 'guy'. 
not sure what's causing it to be on at all with those unchecked

**Comment by ThereforeGames** [comment]
Hi @gsgoldma,

I cannot reproduce this in the latest version of Unprompted - it was likely fixed at some point. Feel free to let me know if `[txt2mask]` still gives you any trouble. Thanks.
