### ISSUE TITLE
Lora inside [file] is not triggered

### ISSUE THREAD

**Issue by ChieVFX** [ThereforeGames/unprompted#71]
Case:
When inside an unprompted file, lora activation tags stop working

How to reproduce:
1) Download a lora (let's say it's name is "2b")
2) Lock seed
3) generate with a prompt <lora:2b:1>
4) create an unprompted temlate file(let's call it "2bt.txt") with the same content: <lora:2b:1>
5) generate with a prompt [file 2bt]

Expected result:
Both prompts are the same, the images generated are the same.

What actually happens:
Both prompts are the same, but the images are very different.

---
If you generate without mentioning lora in prompt, and then generate with [file 2bt], images are practically identical, so including lora in an unprompted file does not do anything :(

**Comment by ChieVFX** [comment]
Let me also explain, why I believe this feature is important.
A lot of characters/clothes are put with loras these days. BUT! Unlike an embedding (which only requires a name), lora is activated with 2 separate things:
1) lora activation tag: <lora:lora_name:lora_weight> (e.g. "<lora:2b:1>")
2) activation tags (e.g. "white hair, short hair, blindfold, black_dress, thighboots")

When dealing with a lot of loras, it's hard to remember their respective activation tags, so putting all of that inside of an unprompted template along with the lora activation tag, would make using loras that much more handy.
Plus, you can make a collection, if lora contains several characters.

Such unprompted templates can be shared along with the loras themselves. This will be benefitial both to the lora usability, and to unprompted's popularity (in my opinion).
Plus, you can share them with a comment under a lora, if the author of lora did not include it anywhere and do not intend to.

Not to mention, that I try to turn all of my prompts to unprompted to make them easier and more dynamic, and this is a serious limitation preventing that :'(

**Comment by ThereforeGames** [comment]
Hi @ChieVFX,

I ran a test on my machine and it looks like you're right - the Lora tags do appear in the final prompt, but they are not being processed by Lora.

I suspect what's happening is that the built-in extensions (of which Lora is one) execute before any third-party extensions such as Unprompted. This is supported by the fact that other shortcodes seem to interfere with the embeddings as well - it's not just `[file]`. For instance, this doesn't work either:

```
<lora:[get my_lora_name]:1>
```

I can possibly try re-running the Lora extension at the end of the Unprompted process. I'm not particularly fond of that solution, but I'm not certain there are other options if this happens to be a limitation of the WebUI.

At any rate, I'll look more deeply into the problem soon and get back to you.

**Comment by ThereforeGames** [comment]
Hi @ChieVFX,

The following PR for the WebUI appears to fix this issue:

https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/7789

It allows me to process Lora tags inside of `[file]`. Feel free to give it a try. Hopefully it gets merged with the main branch!

**Comment by ChieVFX** [comment]
Thanks, I will try it out!
