### ISSUE TITLE
[file] tag does not get a random file from a folder

### ISSUE THREAD

**Issue by ChieVFX** [ThereforeGames/unprompted#72]
According to the manual, [file dirname] should get a random file from that directory, however it produces nothing.

CASE:
I have a following structure in templates:
/pose
- /standing.txt
- /sitting.txt

I use a dry run on the following:
[file pose/standing]
It gives me the content of the file standing.

I use dry run on the following:
[file pose]
It gives me empty string.

I tried also:
[file pose/]
Also gives an empty string.

WHAT SHOULD HAPPEN:
According to documentation, I should've either gotten contents of [file pose/standing] or of [file pose/sitting].
Quote from the manual:
"If the given path is a directory as opposed to a file, [file] will return the contents of a random file in that directory".

**Comment by ThereforeGames** [comment]
Hi @ChieVFX,

Thank you for reaching out!

The documentation needs to be updated. The filepath is parsed with Python's glob module, which means you can choose a file at random using the `*` wildcard, e.g.

```
[file pose/*]
```

...should return either sitting.txt or standing.txt.

**Comment by ChieVFX** [comment]
Oh, nice! Thank you. Good to know.
