### ISSUE TITLE
Error running install.py for extension using either webui methods

### ISSUE THREAD

**Issue by Iggyboo** [ThereforeGames/unprompted#74]
Here is the error message I'm getting when I try and install it on a Linux (ubuntu 20.04) system. I have attempted a fresh install of Automatic1111 to be sure and it still happens. I even made sure to reinstall it into the typical ~/stable-diffusion-webui folder and get the same error.

`Error running install.py for extension /home/user/stable-diffusion-webui1/extensions/unprompted.
Command: "/home/user/stable-diffusion-webui1/venv/bin/python3" "/home/user/stable-diffusion-webui1/extensions/unprompted/install.py"
Error code: 1
stdout: Installing requirements for Unprompted
Installing requirements for Unprompted

stderr: Traceback (most recent call last):
  File "/home/user/stable-diffusion-webui1/extensions/unprompted/install.py", line 6, in <module>
    launch.run_pip("install pattern@git+https://github.com/NicolasBizzozzero/pattern","requirements for Unprompted")
  File "/home/user/stable-diffusion-webui1/launch.py", line 137, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "/home/user/stable-diffusion-webui1/launch.py", line 105, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install requirements for Unprompted.
Command: "/home/user/stable-diffusion-webui1/venv/bin/python3" -m pip install pattern@git+https://github.com/NicolasBizzozzero/pattern --prefer-binary
Error code: 1
stdout: Collecting pattern@ git+https://github.com/NicolasBizzozzero/pattern
  Cloning https://github.com/NicolasBizzozzero/pattern to /tmp/pip-install-3mwgs0so/pattern_2b70c3975485418c88674499d28d466c
  Resolved https://github.com/NicolasBizzozzero/pattern to commit 66ab34453a3443c06a4ebda092c8d1947c83b17a
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting backports.csv
  Using cached backports.csv-1.0.7-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: beautifulsoup4 in ./venv/lib/python3.10/site-packages (from pattern@ git+https://github.com/NicolasBizzozzero/pattern) (4.11.2)
Collecting cherrypy
  Using cached CherryPy-18.8.0-py2.py3-none-any.whl (348 kB)
Collecting feedparser
  Using cached feedparser-6.0.10-py3-none-any.whl (81 kB)
Requirement already satisfied: future in ./venv/lib/python3.10/site-packages (from pattern@ git+https://github.com/NicolasBizzozzero/pattern) (0.18.3)
Collecting lxml
  Using cached lxml-4.9.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (7.1 MB)
Collecting mysqlclient
  Using cached mysqlclient-2.1.1.tar.gz (88 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

stderr:   Running command git clone --filter=blob:none --quiet https://github.com/NicolasBizzozzero/pattern /tmp/pip-install-3mwgs0so/pattern_2b70c3975485418c88674499d28d466c
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      /bin/sh: 1: mysql_config: not found
      /bin/sh: 1: mariadb_config: not found
      /bin/sh: 1: mysql_config: not found
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-3mwgs0so/mysqlclient_20a2fa184a424aa7a0e2b170a7f02251/setup.py", line 15, in <module>
          metadata, options = get_config()
        File "/tmp/pip-install-3mwgs0so/mysqlclient_20a2fa184a424aa7a0e2b170a7f02251/setup_posix.py", line 70, in get_config
          libs = mysql_config("libs")
        File "/tmp/pip-install-3mwgs0so/mysqlclient_20a2fa184a424aa7a0e2b170a7f02251/setup_posix.py", line 31, in mysql_config
          raise OSError("{} not found".format(_mysql_config_path))
      OSError: mysql_config not found
      mysql_config --version
      mariadb_config --version
      mysql_config --libs
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
`

**Comment by TaciteOFF** [comment]
I had similar issue before installing mysql by myself on my MacBook.
Now new errors:

```
Error running install.py for extension /Users/XXX/Downloads/stable-diffusion-webui/extensions/unprompted.
Command: "/Users/XXX/Downloads/stable-diffusion-webui/venv/bin/python3.10" "/Users/XXX/Downloads/stable-diffusion-webui/extensions/unprompted/install.py"
Error code: 1
stdout: Installing requirements for Unprompted - img2pez
Installing requirements for Unprompted - pix2pix_zero

stderr: Traceback (most recent call last):
  File "/Users/XXX/Downloads/stable-diffusion-webui/extensions/unprompted/install.py", line 10, in <module>
    launch.run_pip("install salesforce-lavis","requirements for Unprompted - pix2pix_zero")
  File "/Users/XXX/Downloads/stable-diffusion-webui/launch.py", line 137, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "/Users/XXX/Downloads/stable-diffusion-webui/launch.py", line 105, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install requirements for Unprompted - pix2pix_zero.
Command: "/Users/XXX/Downloads/stable-diffusion-webui/venv/bin/python3.10" -m pip install salesforce-lavis --prefer-binary
Error code: 1
stdout: Collecting salesforce-lavis
  Using cached salesforce_lavis-1.0.0-py3-none-any.whl (495 kB)
Collecting ipython
  Using cached ipython-8.10.0-py3-none-any.whl (784 kB)
Requirement already satisfied: einops>=0.4.1 in ./venv/lib/python3.10/site-packages (from salesforce-lavis) (0.4.1)
Requirement already satisfied: wheel in ./venv/lib/python3.10/site-packages (from salesforce-lavis) (0.38.4)
Requirement already satisfied: omegaconf in ./venv/lib/python3.10/site-packages (from salesforce-lavis) (2.2.3)
Collecting streamlit
  Using cached streamlit-1.18.1-py2.py3-none-any.whl (9.6 MB)
Collecting opendatasets
  Using cached opendatasets-0.1.22-py3-none-any.whl (15 kB)
Requirement already satisfied: packaging in ./venv/lib/python3.10/site-packages (from salesforce-lavis) (23.0)
Requirement already satisfied: ftfy in ./venv/lib/python3.10/site-packages (from salesforce-lavis) (6.1.1)

stderr: ERROR: Ignored the following versions that require a different python version: 0.55.2 Requires-Python <3.5
ERROR: Could not find a version that satisfies the requirement decord (from salesforce-lavis) (from versions: none)
ERROR: No matching distribution found for decord

```

So it's probably because it's not compatible with MacOS ARM (M1)

**Comment by ThereforeGames** [comment]
Hi guys,

It looks like this error is related to a dependency for the `[pix2pix_zero]` shortcode. Honestly, I wasn't thrilled with the quality of pix2pix_zero so I may simply remove it in a future update - especially if it's causing problems on some operating systems.

In the meantime, though, you can cut the following lines from `unprompted/install.py`:

```
if not launch.is_installed("salesforce-lavis"):
	launch.run_pip("install salesforce-lavis","requirements for Unprompted - pix2pix_zero")
```

Let me know if that helps.

**Comment by ewebgh33** [comment]
I removed those two lines and stopped getting the error. Tried installing for the first time yesterday.
So this only disables pix2pix? If so, not a big deal as I have another extension that does that.
TBH extensions don't need to include EVERYTHING, just the main thing they are meant to do, so any pix2pix should be a separate thing anyway? IMO
That said, I installed this to try out PEZ, so...

**Comment by leonardofelin** [comment]
> Hi guys,
> 
> It looks like this error is related to a dependency for the `[pix2pix_zero]` shortcode. Honestly, I wasn't thrilled with the quality of pix2pix_zero so I may simply remove it in a future update - especially if it's causing problems on some operating systems.
> 
> In the meantime, though, you can cut the following lines from `unprompted/install.py`:
> 
> ```
> if not launch.is_installed("salesforce-lavis"):
> 	launch.run_pip("install salesforce-lavis","requirements for Unprompted - pix2pix_zero")
> ```
> 
> Let me know if that helps.

I had the same error showing up (Windows 10 here). Removing the two lines from the install file fixed it.

**Comment by voshed** [comment]
Also got a similar issue with pix2pix_zero. Removing the lines helps.

**Comment by Soulreaver90** [comment]
I ran into the topmost MYSQL error. Had to install the following on my machine
`sudo apt-get install python3-dev libmysqlclient-dev`
Then it installed just fine. Might need to include this on the main page or as an error output instead of the jumble error mysql produces.

**Comment by ThereforeGames** [comment]
Closing as the `[pix2pix_zero]` shortcode was retired.
