### ISSUE TITLE
Can't load unprompted extension in Automatic1111 when emojis are present in templates 😢

### ISSUE THREAD

**Issue by kylechallis** [ThereforeGames/unprompted#79]
The interesting thing here is that as long as you put in the emojis _after_ the extension is loaded, it works fine and dandy 🥳

To reproduce:
1. Put an emoji in a file in your templates directory. I know 😍 "works" for breaking things.
2. Try to start Automatic1111 via `user-webui.bat` *or* enable the extension in the A1111 extensions view (and reload the UI).

Expected behavior: Unprompted loads with no problems.

Actual behavior: Unprompted fails to load and yields a "TypeError: Scripts.process() missing 2 required positional arguments: 'is_enabled' and 'unprompted_seed'" error.

As a side note, I found it particularly interesting that this breaks things because the only reason I found this is by using [img2pez], which frequently yields emojis.

**Comment by ThereforeGames** [comment]
👉Fixed 👀🤯✅✅✅👌
