### ISSUE TITLE
Ads

### ISSUE THREAD

**Issue by JohnWJarrett** [ThereforeGames/unprompted#8]
Hey, so yeah, can you get rid of the ad, it's annoying, like I get it, you need money for food and whatnot, but I gave you that (Got the thing it's advertising) so... yeah, can I not see the ad please.

Thanks, -J

**Comment by ThereforeGames** [comment]
Hi @JohnWJarrett,

First, thank you for your support!

I have released an update for Unprompted that adds a "Dismiss Ad" button to the UI. The ad will be hidden by default since you have already purchase the Fantasy Card Template.
