### ISSUE TITLE
can you make a file-choose?

### ISSUE THREAD

**Issue by IkariDevGIT** [ThereforeGames/unprompted#81]
basically chooses a random line in a file without the need of the [choose][/choose] in the file(like the normal wildcards)

in a format like this:
![grafik](https://user-images.githubusercontent.com/90197782/222464772-fdab0c1d-283f-408e-8fe7-2979d9ce576d.png)

**Comment by IkariDevGIT** [comment]
@ThereforeGames please bro

**Comment by scrumpyman** [comment]
This is also what prevents me from trying this extension. I don't want to make a separate version of my wildcards for this or dynamic prompts, and apply modifications to both.
Any reason [choose] isn't used by default on a file with newlines and no instruction?

**Comment by IkariDevGIT** [comment]
@ThereforeGames please bro

**Comment by ThereforeGames** [comment]
Hi @IkariDevGIT and @scrumpyman,

As of Unprompted v9.0.0, the following syntax will pick a random line from `somefile`:

```
[choose][file somefile][/choose]
```

Let me know if you have any questions.

**Comment by IkariDevGIT** [comment]
thx bro
