### ISSUE TITLE
[img2pez]

### ISSUE THREAD

**Issue by NorTroll** [ThereforeGames/unprompted#82]
img2pez does not apply prompts to images after the first one if doing several batches or higher batch numbers.

**Comment by demirklvc** [comment]
same issue

**Comment by ThereforeGames** [comment]
Hi @NorTroll and @demirklvc,

There is a conflict between the Hard Prompts Made Easy library and WebUI batch processing. I'm not familiar enough with Torch to solve the underlying problem, but I was able to work around it by having `[img2pez]` implement its own batching. The downside here is that we can't modify the `[img2pez]` settings mid-run, but at least it won't crash anymore. Available in Unprompted v9.15.0.

I may try to get in touch with the library's author to see if we can figure out a better solution long-term.
