### ISSUE TITLE
Avalaible clip model for img2pez

### ISSUE THREAD

**Issue by HeavyTony2** [ThereforeGames/unprompted#83]
The wizard lists two models, however, one of them isn't avalaible
`RuntimeError: Model ViT-H-14 not found; available models = ['RN50', 'RN50-quickgelu', 'RN101', 'RN101-quickgelu', 'RN50x4', 'RN50x16', 'RN50x64', 'ViT-B-32', 'ViT-B-32-quickgelu', 'ViT-B-16', 'ViT-L-14', 'ViT-L-14-336']`

**Comment by HeavyTony2** [comment]
Similar issue for pretrain
`RuntimeError: Pretrained weights (laion2b_s32b_b79k) not found for model ViT-L-14.Available pretrained tags (['openai', 'laion400m_e31', 'laion400m_e32', 'laion2b_s32b_b82k'].`

**Comment by ThereforeGames** [comment]
Hi @HeavyTony2,

Thank you for reaching out!

At the moment, the CLIP Model setting must correspond with the correct CLIP Pretrain setting, e.g. **ViT-L-14 + openai** or **ViT-H-14 + laion2b_s32b_b79k**. It only throws an error if mismatched.

I may compress these into one setting eventually, but I need to make sure there aren't other possible model/pretrain combinations first.
