### ISSUE TITLE
batch generate mask

### ISSUE THREAD

**Issue by tembel123456** [ThereforeGames/unprompted#86]
hello... when use txt2mask, batch mode, in output folder i'am get only mask for first image and other images, are just result, without mask...  how to generate masks for all images?

thanx

**Comment by tembel123456** [comment]
any help, how create and save mask for all images, from batch ?

**Comment by RuKapSan** [comment]
same problem

**Comment by ThereforeGames** [comment]
Hi @tembel123456 and @RuKapSan,

The `[txt2mask]` shortcode has since been updated with better support for batch processing. Let me know if it still gives you any trouble. Thanks.
