### ISSUE TITLE
Throws errors with any extensions that add to the txt2img tab

### ISSUE THREAD

**Issue by djkacevedo** [ThereforeGames/unprompted#87]
```
Error running process: D:\dev\stable-diffusion-webui-main\extensions\cuttoff-cutting-off-prompt-effect\scripts\cutoff.py
Traceback (most recent call last):
  File "D:\dev\stable-diffusion-webui-main\modules\scripts.py", line 409, in process
    script.process(p, *script_args)
TypeError: Script.process() missing 7 required positional arguments: 'enabled', 'targets_', 'weight', 'strong', 'padding', 'intp', and 'debug'
```
So far, I've seen that with cutoff, two-shot, composable loras, and asymmetrical tiling. It throws the error if I use any shortcode.

The generation seems to be fine though.

**Comment by ThereforeGames** [comment]
Hi,

I have implemented a fix for this in v7.8.0 - the `[img2img]` shortcode will temporarily bypass always_on scripts to avoid such errors. Please try updating the extension and let me know if the issue persists. Thank you!
