### ISSUE TITLE
Collapsible menu and advertising

### ISSUE THREAD

**Issue by Harvester62** [ThereforeGames/unprompted#9]
Hello, I like your custom script but I wish to suggest you to make it collapsible, like aesthetic-gradients because, frankly, that AD is a little bit invasive in the UI. I do understand the reason to have it and I have nothing in contrary, but I would appreciate to have the menu collapsed by default, or to be able to collapse it. Do you think it might be feasible? Would you consider it? 
Thank you for your attention and consideration.

**Comment by ThereforeGames** [comment]
Hi @Harvester62,

Thank you for your feedback! I have released an update for Unprompted that adds a "Dismiss Ad" button to the UI.

If you purchase the Fantasy Card Template, it will hide the ad for you automatically.
