### ISSUE TITLE
img2pez does not apply prompts to images after the first one if doing several batches or higher batch numbers.

### ISSUE THREAD

**Issue by demirklvc** [ThereforeGames/unprompted#99]
Please fix. it makes it not very usable like that.
<img width="1440" alt="Bildschirmfoto 2023-03-15 um 14 49 31" src="https://user-images.githubusercontent.com/78754525/225328969-d972abd0-7a9b-455d-aa7e-909ef8d9595d.png">

**Comment by demirklvc** [comment]
@ThereforeGames

**Comment by demirklvc** [comment]
yeah just ignore the issue. ......

**Comment by ThereforeGames** [comment]
Duplicate of #82
